// Copyright (c) 2026 Richard Rodger and other contributors, MIT License

// Parity with the canonical TypeScript, recorded.
//
// `tests/oracle/gbnf-oracle.json` holds what `ts/dist` answered for 210
// sources: every construct the notation has, every refusal, all eight
// llama.cpp corpus grammars and all seventy schema-generated ones. For
// each source it records the IR (source spans included), the rendered
// GBNF, and the parts of the emitted spec this front-end owns: the match
// tokens with their eager flags, the computed `lex.empty`, and the rule
// names.
//
// This file holds the port to it. The oracle is regenerated by
// `tests/oracle/gen-oracle.js` from a built `ts/`, so a change in the
// canonical implementation arrives here as a red test rather than as
// silence.
//
// A span is compared as the TEXT it covers, never as a raw offset:
// TypeScript counts UTF-16 code units and this port counts bytes (a
// recorded divergence), and slicing the source with the span is the only
// comparison worth making anyway. An offset pair that is self-consistent
// but points at the wrong characters would satisfy any assertion about
// the numbers themselves. `go/spans_test.go` says the same.

mod common;

use std::collections::BTreeMap;
use std::path::Path;

use serde_json::{json, Map, Value as Json};
use tabnas_gbnf::{gbnf_convert, parse_gbnf, render_gbnf, GbnfError};

use common::no_spans;

/// An entry the oracle could not record, because the canonical answer
/// holds an unpaired surrogate and JSON cannot carry one. Each is a
/// recorded DIVERGENCE (DIVERGENCE.md 1), refused by name here, and
/// `tests/divergence_test.rs` pins it in BOTH directions so an exemption
/// cannot quietly widen.
fn unrepresentable(entry: &Map<String, Json>) -> bool {
    entry.contains_key("unrepresentable")
}

fn oracle() -> Vec<Map<String, Json>> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("oracle")
        .join("gbnf-oracle.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("{}: {error}", path.display()));
    let entries: Vec<Json> = serde_json::from_str(&text).expect("the oracle is JSON");
    entries
        .into_iter()
        .map(|entry| match entry {
            Json::Object(map) => map,
            other => panic!("an oracle entry is not an object: {other}"),
        })
        .collect()
}

fn text_of(entry: &Map<String, Json>, key: &str) -> Option<String> {
    entry.get(key).and_then(Json::as_str).map(str::to_string)
}

/// Rewrite the IR the way `gen-oracle.js` does: keys sorted, every `sp`
/// replaced by the text it covers plus its row and column, and an
/// unbounded repetition bound spelled the way `JSON.stringify` spells
/// `Infinity` there.
fn normalize(value: &Json, src: &str) -> Json {
    match value {
        Json::Array(items) => Json::Array(items.iter().map(|item| normalize(item, src)).collect()),
        Json::Object(entries) => {
            let unbounded = Some("rep") == entries.get("kind").and_then(Json::as_str);
            let mut out: BTreeMap<String, Json> = BTreeMap::new();
            for (key, item) in entries {
                // `nodeKind` is the shared compiler's annotation slot, and
                // `user` is its default. TypeScript leaves the field off a
                // production nobody annotated; this runtime spells the
                // default out. Same IR, one serializer writing a default
                // the other omits, so the default is dropped rather than
                // compared.
                if "nodeKind" == key && Some("user") == item.as_str() {
                    continue;
                }
                if "sp" == key {
                    if let Some(span) = span_text(item, src) {
                        out.insert(key.clone(), span);
                        continue;
                    }
                }
                if unbounded && "max" == key && item.is_null() {
                    out.insert(key.clone(), json!("Infinity"));
                    continue;
                }
                out.insert(key.clone(), normalize(item, src));
            }
            Json::Object(out.into_iter().collect())
        }
        other => other.clone(),
    }
}

/// A span as `{c, r, t}`, where `t` is the source text it covers.
///
/// The offsets are this runtime's, so they are BYTES. Slicing without
/// checking would panic on a multibyte tail; a span that does not land on
/// character boundaries is reported as such, so the case fails with a
/// diagnosis rather than a backtrace.
///
/// The COLUMN is converted rather than copied. The engine reports it in
/// Unicode scalar values and the canonical runtime reports it in UTF-16
/// code units, which differ from the first astral character on a line
/// onwards: a recorded divergence (DIVERGENCE.md 2), and one this port
/// inherits rather than makes. Converting states the relationship exactly
/// instead of weakening the comparison, and
/// `the_column_the_engine_reports_counts_characters` pins the other half,
/// that the engine's own number is the character column.
fn span_text(span: &Json, src: &str) -> Option<Json> {
    let start = span.get("s")?.as_u64()? as usize;
    let end = span.get("e")?.as_u64()? as usize;
    let covered = if start <= end
        && end <= src.len()
        && src.is_char_boundary(start)
        && src.is_char_boundary(end)
    {
        Json::String(src[start..end].to_string())
    } else {
        json!(format!("<not a character range: {start}..{end}>"))
    };
    Some(json!({
        "c": match line_prefix(src, start) {
            Some(prefix) => json!(1 + prefix.chars().map(char::len_utf16).sum::<usize>()),
            None => span.get("c").cloned().unwrap_or(Json::Null),
        },
        "r": span.get("r").cloned().unwrap_or(Json::Null),
        "t": covered,
    }))
}

/// The text from the start of `at`'s line up to `at`, or `None` when the
/// offset is not a character boundary of `src`.
fn line_prefix(src: &str, at: usize) -> Option<&str> {
    if src.len() < at || !src.is_char_boundary(at) {
        return None;
    }
    let head = &src[..at];
    Some(match head.rfind('\n') {
        Some(newline) => &head[newline + 1..],
        None => head,
    })
}

/// The other half of DIVERGENCE.md 2, measured over every span in the
/// oracle: the number the engine reports is the CHARACTER column, so the
/// conversion above is a conversion and not a fudge.
#[test]
fn the_column_the_engine_reports_counts_characters() {
    let mut wrong: Vec<String> = Vec::new();
    let mut checked = 0usize;
    for entry in oracle() {
        let name = text_of(&entry, "name").expect("named");
        let src = text_of(&entry, "src").expect("sourced");
        let Ok(grammar) = parse_gbnf(&src) else {
            continue;
        };
        let value = serde_json::to_value(&grammar).expect("serializes");
        let mut spans: Vec<Json> = Vec::new();
        collect_spans(&value, &mut spans);
        for span in spans {
            let (Some(start), Some(row), Some(column)) = (
                span.get("s").and_then(Json::as_u64),
                span.get("r").and_then(Json::as_u64),
                span.get("c").and_then(Json::as_u64),
            ) else {
                continue;
            };
            let start = start as usize;
            let Some(prefix) = line_prefix(&src, start) else {
                wrong.push(format!(
                    "{name}: span offset {start} is not a character boundary"
                ));
                continue;
            };
            let want_column = 1 + prefix.chars().count();
            let want_row = 1 + src[..start].matches('\n').count();
            if column as usize != want_column {
                wrong.push(format!(
                    "{name}: column {column} at offset {start}, want {want_column}"
                ));
            }
            if row as usize != want_row {
                wrong.push(format!(
                    "{name}: row {row} at offset {start}, want {want_row}"
                ));
            }
            checked += 1;
        }
    }
    assert!(1000 < checked, "only {checked} spans were checked");
    assert!(
        wrong.is_empty(),
        "{}\n{} cases",
        wrong.join("\n"),
        wrong.len()
    );
}

fn collect_spans(value: &Json, out: &mut Vec<Json>) {
    match value {
        Json::Array(items) => items.iter().for_each(|item| collect_spans(item, out)),
        Json::Object(entries) => {
            for (key, item) in entries {
                if "sp" == key && item.is_object() {
                    out.push(item.clone());
                } else {
                    collect_spans(item, out);
                }
            }
        }
        _ => {}
    }
}

/// The canonical `/\x1b\[[0-9;]*m/g`, spelled out.
fn strip_ansi(text: &str) -> String {
    let characters: Vec<char> = text.chars().collect();
    let mut out = String::with_capacity(text.len());
    let mut i = 0usize;
    while i < characters.len() {
        if '\u{1b}' == characters[i] && Some(&'[') == characters.get(i + 1) {
            let mut j = i + 2;
            while j < characters.len() && (characters[j].is_ascii_digit() || ';' == characters[j]) {
                j += 1;
            }
            if j < characters.len() && 'm' == characters[j] {
                i = j + 1;
                continue;
            }
        }
        out.push(characters[i]);
        i += 1;
    }
    out
}

fn ir_json(src: &str) -> Result<Json, GbnfError> {
    let grammar = parse_gbnf(src)?;
    let value = serde_json::to_value(&grammar).expect("the IR serializes");
    Ok(normalize(&value, src))
}

// ---- the IR ------------------------------------------------------------

#[test]
fn every_source_answers_what_the_typescript_answered() {
    let mut wrong: Vec<String> = Vec::new();
    let mut compared = 0usize;

    for entry in oracle() {
        let name = text_of(&entry, "name").expect("every entry is named");
        let src = text_of(&entry, "src").expect("every entry carries its source");
        if unrepresentable(&entry) {
            assert!(
                parse_gbnf(&src).is_err(),
                "{name}: DIVERGENCE.md 1 says this source is refused here, and it was not"
            );
            continue;
        }
        compared += 1;

        match (entry.get("ir"), entry.get("parseError")) {
            (Some(expected), None) => match ir_json(&src) {
                Ok(actual) => {
                    if &actual != expected {
                        wrong.push(format!(
                            "{name}: IR differs\n  want {expected}\n  got  {actual}"
                        ));
                    }
                }
                Err(error) => {
                    wrong.push(format!("{name}: refused, but TypeScript parsed: {error}"))
                }
            },
            (None, Some(expected)) => match parse_gbnf(&src) {
                Ok(_) => wrong.push(format!(
                    "{name}: parsed, but TypeScript refused: {expected}"
                )),
                Err(error) => {
                    if let Some(complaint) = compare_error(&name, expected, &error) {
                        wrong.push(complaint);
                    }
                }
            },
            _ => panic!("{name}: the oracle records neither an IR nor a refusal"),
        }
    }

    assert!(
        100 < compared,
        "only {compared} sources were compared; the oracle is too small to mean anything"
    );
    assert!(
        wrong.is_empty(),
        "{}\n{} cases",
        wrong.join("\n"),
        wrong.len()
    );
}

fn compare_error(name: &str, expected: &Json, actual: &GbnfError) -> Option<String> {
    let want_name = expected.get("name").and_then(Json::as_str).unwrap_or("");
    let want_message = expected.get("message").and_then(Json::as_str).unwrap_or("");
    // The engine colours its diagnostics for a terminal in BOTH
    // runtimes, and the oracle records them without the escapes, exactly
    // as the command's report carries them. Strip here for the same
    // reason rather than comparing one runtime's escapes with the
    // other's absence of them.
    let got_message = strip_ansi(&actual.to_string());

    if want_name != actual.name() {
        return Some(format!(
            "{name}: error class is {}, want {want_name}",
            actual.name()
        ));
    }

    // The WHOLE sentence, whoever wrote it. This front-end's own
    // diagnostics are ports of the canonical ones word for word, and the
    // engine's turn out to be identical in the two runtimes as well, so
    // there is nothing here to excuse.
    if want_message != got_message {
        return Some(format!(
            "{name}: message differs\n  want {want_message:?}\n  got  {got_message:?}"
        ));
    }

    let want_rule = expected.get("rule").and_then(Json::as_str);
    if want_rule != actual.rule() {
        return Some(format!(
            "{name}: rule is {:?}, want {want_rule:?}",
            actual.rule()
        ));
    }
    let want_line = expected
        .get("line")
        .and_then(Json::as_u64)
        .map(|n| n as usize);
    if want_line != actual.line() {
        return Some(format!(
            "{name}: line is {:?}, want {want_line:?}",
            actual.line()
        ));
    }
    let want_column = expected
        .get("column")
        .and_then(Json::as_u64)
        .map(|n| n as usize);
    if want_column != actual.column() {
        return Some(format!(
            "{name}: column is {:?}, want {want_column:?}",
            actual.column()
        ));
    }
    None
}

// ---- the renderer ------------------------------------------------------

#[test]
fn every_source_renders_what_the_typescript_rendered() {
    let mut wrong: Vec<String> = Vec::new();
    for entry in oracle() {
        let name = text_of(&entry, "name").expect("named");
        let src = text_of(&entry, "src").expect("sourced");
        let Some(expected) = text_of(&entry, "render") else {
            continue;
        };
        let Ok(grammar) = parse_gbnf(&src) else {
            wrong.push(format!("{name}: does not parse here"));
            continue;
        };
        match render_gbnf(&grammar, None) {
            Ok(actual) if actual == expected => {}
            Ok(actual) => wrong.push(format!(
                "{name}: render differs\n  want {expected:?}\n  got  {actual:?}"
            )),
            Err(error) => wrong.push(format!("{name}: refused to render: {error}")),
        }
    }
    assert!(
        wrong.is_empty(),
        "{}\n{} cases",
        wrong.join("\n"),
        wrong.len()
    );
}

/// Parse, render, parse. The renderer chooses surface spellings, never
/// meanings, so the second IR is the first one with the spans moved.
/// Measured over every source the oracle carries, both corpora included.
#[test]
fn rendering_and_reparsing_is_a_fixed_point() {
    let mut wrong: Vec<String> = Vec::new();
    let mut checked = 0usize;
    for entry in oracle() {
        let src = text_of(&entry, "src").expect("sourced");
        let name = text_of(&entry, "name").expect("named");
        if entry.get("ir").is_none() {
            continue;
        }
        let Ok(grammar) = parse_gbnf(&src) else {
            wrong.push(format!("{name}: does not parse here"));
            continue;
        };
        let text = match render_gbnf(&grammar, None) {
            Ok(text) => text,
            Err(error) => {
                wrong.push(format!("{name}: refused to render: {error}"));
                continue;
            }
        };
        let again = match parse_gbnf(&text) {
            Ok(again) => again,
            Err(error) => {
                wrong.push(format!("{name}: the rendering does not reparse: {error}"));
                continue;
            }
        };
        let before = no_spans(serde_json::to_value(&grammar).expect("serializes"));
        let after = no_spans(serde_json::to_value(&again).expect("serializes"));
        if before != after {
            wrong.push(format!("{name}: not a fixed point\n  {text:?}"));
        }
        checked += 1;
    }
    assert!(100 < checked, "only {checked} grammars round-tripped");
    assert!(
        wrong.is_empty(),
        "{}\n{} cases",
        wrong.join("\n"),
        wrong.len()
    );
}

// ---- the emitted spec --------------------------------------------------

/// The match tokens the spec carries, their patterns and their eager
/// flags, plus the computed `lex.empty` and the rule names.
///
/// The eager flags are the interesting half: `mark_classes_eager` drops
/// the engine's rule-directed gate only when a grammar's classes are
/// pairwise disjoint AND no class holds the first character of a literal,
/// and the two conditions are checked over the whole grammar. Every
/// corpus grammar exercises them.
#[test]
fn every_source_emits_the_spec_the_typescript_emitted() {
    let mut wrong: Vec<String> = Vec::new();
    for entry in oracle() {
        let name = text_of(&entry, "name").expect("named");
        let src = text_of(&entry, "src").expect("sourced");
        let Some(Json::Array(expected)) = entry.get("matchTokens") else {
            continue;
        };
        let spec = match gbnf_convert(&src, None) {
            Ok(spec) => spec,
            Err(error) => {
                wrong.push(format!("{name}: does not compile here: {error}"));
                continue;
            }
        };

        let tokens = spec
            .options
            .get("match")
            .and_then(|matchers| matchers.get("token"))
            .and_then(Json::as_object)
            .cloned()
            .unwrap_or_default();

        let got: Vec<(String, String, bool)> = tokens
            .iter()
            .map(|(key, value)| {
                let serialized = value.as_str().unwrap_or_default();
                let eager = serialized.starts_with("@~/");
                let body = serialized
                    .strip_prefix("@~/")
                    .or_else(|| serialized.strip_prefix("@/"))
                    .unwrap_or(serialized);
                let source = body.rfind('/').map_or(body, |at| &body[..at]);
                (key.clone(), source.to_string(), eager)
            })
            .collect();

        let want: Vec<(String, String, bool)> = expected
            .iter()
            .map(|token| {
                (
                    token
                        .get("name")
                        .and_then(Json::as_str)
                        .unwrap_or_default()
                        .to_string(),
                    token
                        .get("source")
                        .and_then(Json::as_str)
                        .unwrap_or_default()
                        .to_string(),
                    token.get("eager").and_then(Json::as_bool).unwrap_or(false),
                )
            })
            .collect();

        if got != want {
            wrong.push(format!(
                "{name}: match tokens differ\n  want {want:?}\n  got  {got:?}"
            ));
        }

        let want_empty = entry
            .get("lexEmpty")
            .and_then(Json::as_bool)
            .unwrap_or(false);
        let got_empty = spec
            .options
            .get("lex")
            .and_then(|lex| lex.get("empty"))
            .and_then(Json::as_bool)
            .unwrap_or(false);
        if want_empty != got_empty {
            wrong.push(format!(
                "{name}: lex.empty is {got_empty}, want {want_empty}"
            ));
        }

        if let Some(Json::Array(names)) = entry.get("ruleNames") {
            let want: Vec<&str> = names.iter().filter_map(Json::as_str).collect();
            let got: Vec<&str> = spec.rule.keys().map(String::as_str).collect();
            if want != got {
                wrong.push(format!(
                    "{name}: rule names differ\n  want {want:?}\n  got  {got:?}"
                ));
            }
        }
    }
    assert!(
        wrong.is_empty(),
        "{}\n{} cases",
        wrong.join("\n"),
        wrong.len()
    );
}

// ---- the oracle itself -------------------------------------------------

/// A corpus of one kind would let the other rot, and an oracle that
/// quietly shrank would take the parity claim with it.
#[test]
fn the_oracle_is_present_and_covers_both_answers() {
    let entries = oracle();
    assert!(
        200 <= entries.len(),
        "the oracle carries only {} entries",
        entries.len()
    );
    let parsed = entries.iter().filter(|e| e.contains_key("ir")).count();
    let refused = entries
        .iter()
        .filter(|e| e.contains_key("parseError"))
        .count();
    assert!(100 < parsed, "only {parsed} accepted sources");
    assert!(20 < refused, "only {refused} refused sources");

    // Both committed corpora are in it, by name.
    let names: Vec<String> = entries
        .iter()
        .filter_map(|entry| text_of(entry, "name"))
        .collect();
    assert_eq!(
        8,
        names.iter().filter(|n| n.starts_with("corpus/")).count(),
        "the eight llama.cpp grammars are not all in the oracle"
    );
    assert_eq!(
        70,
        names.iter().filter(|n| n.starts_with("live/")).count(),
        "the seventy schema-generated grammars are not all in the oracle"
    );
}
