/* Copyright (c) 2026 Richard Rodger and other contributors, MIT License */

// Generated by ../embed-translate.js. Edit tabnas.plugin.json or alchemy/*,
// then run npm run embed.

type TranslationPart = Readonly<{
  entry: string
  source?: string
}>

type TranslationParts = Readonly<{
  manifest: string
  lift?: TranslationPart
  embed?: TranslationPart
  render?: TranslationPart
}>

const TRANSLATION: TranslationParts = Object.freeze({
  manifest: `{
  "$schema": "https://tabnas.dev/schema/plugin.schema.json",
  "name": "@tabnas/gbnf",
  "go": "github.com/tabnas/gbnf/go",
  "rust": "tabnas-gbnf",
  "description": "llama.cpp GBNF grammar compiler for the tabnas engine. A host reads a GBNF document by compiling it: the tree it translates is the pure-data GrammarSpec the compiler emits (schema grammar-spec), which the render writes back as GBNF.",
  "base": "@tabnas/bnf",
  "engine": "@tabnas/parser",
  "extensions": [
    ".gbnf"
  ],
  "languageId": "gbnf",
  "clib": {
    "dir": "go/clib",
    "library": "libtabnasgbnf",
    "abi": "v1",
    "errorCodes": [
      "usage",
      "grammar",
      "handle",
      "internal"
    ]
  },
  "errorCodes": [],
  "docs": "https://tabnas.dev/docs/packages",
  "repository": "https://github.com/tabnas/gbnf",
  "versionSource": "ts/package.json",
  "translate": {
    "reads": "tree",
    "writes": "tree",
    "root": "object",
    "schema": "grammar-spec",
    "render": "alchemy/render.alc",
    "loss": [
      "The grammar is written anew from its compiled spec: comments, blank lines and layout are not kept, and each rule is written on one line.",
      "A rule is written as the compiler rewrote it: a reference that led an alternative is written back where the alternatives the compiler put in its place still stand together, each followed by one same tail, and is otherwise written as those alternatives; a left recursion is written as the repetition it became, and alternatives the compiler left-factored with their shared prefix written in each of them again.",
      "Where the compiler reordered a rule's alternatives to tell them apart (a longer lookahead ahead of a shorter one that begins with the same character, a keyword ahead of a character class that can take it), the alternatives that push a helper of the compiler's are put back in the order its numbers record, and the others are written in the compiled order: the rule compiles back the same, and the spec compiled back can differ in the order of the alternates other rules build through it, in the numbers of the compiler's helpers and in the order of its tokens.",
      "A left recursion that ran through another rule (a ::= b, b ::= a \\"+\\" | n) is written as the compiler rewrote it, with the leading reference that closed the cycle left in place, and compiles back to another spec, since the compiler now substitutes that reference.",
      "GBNF starts from the rule named root: a spec whose start rule has another name is written with root ::= and that name first, as render_gbnf writes it, and compiles back with that rule added; a spec that has a rule named root that is not its start rule is refused.",
      "Terminals are written in GBNF's forms, spelled as render_gbnf spells them: a literal as a string, a class as a bracket expression and [\\\\s\\\\S] as a dot, and a rule the compiler made a token of (plus ::= \\"+\\", referenced as plus) as that rule, after the others.",
      "A rule the compiler made a token of, whose name is one the compiler could give its literal by itself (B ::= \\"b\\", or any name of capitals, digits and underscores where the literal holds a character past ASCII), cannot be told from that literal and is written as the literal: it compiles back with the token later in the token table, or under the name the literal gives it.",
      "Repetitions are written in GBNF's forms, x*, x+, x?, x{m}, x{m,} and x{m,n}, with a postfix on a postfix (x*?) where a repetition is itself repeated.",
      "An empty alternative is written as nothing between its bars; in a rule whose alternatives the compiler emits as its open alternates, where it puts the empty one last wherever it stood, it is written first, as llama.cpp's grammars write it.",
      "A spec compiled from another notation compiles back under GBNF's own settings: the group tag on every alternate and GBNF's exact lexing are GBNF's, a case-insensitive literal (ABNF's default) is written as the two-case classes and strings that match exactly what it matches, an RFC 5234 core rule is written as a rule of its own, and an empty literal, which GBNF reads as nothing, as an empty string.",
      "The tree builders every compiled grammar carries (@node$, @capture$, @bubble$ and @fold$, with their k settings) and its marks are not written, since the compiler makes them again from the rules: a spec whose builders or marks are others compiles back with the compiler's own, and recognises what it recognised.",
      "A spec the render cannot write as GBNF is refused with TARGET_VALUE_UNREPRESENTABLE, naming what it met: an action (a value annotation's builders, a user action, the probe dispatcher of an optional prefix), a condition or a counter other than a repetition's, an error generator or an alternate modifier, a function reference where a rule or a count is due, a set of tokens at one place, a removal, a clear or the form that edits a rule already installed, a token no GBNF terminal matches (the engine's own TX, NR, ST and VL, a class whose flags change what it matches (no u on a class that is negated, reaches past U+FFFF or holds every code point, or u on one that holds a surrogate), a pattern that is neither one class nor an escaped literal, a case-insensitive literal holding a character past ASCII that may have cases: one of the Basic Multilingual Plane, or of a script past it that has them), a token set whose tokens are not the class its name gives, a rule with no alternate to open with, a sequence's step with more alternates than a step, a rule the compiler lifted to a token whose name another rule holds, a rule name GBNF cannot spell, the empty name among them, a repetition bounded past what the compiler numbers, a repetition of no copies, whose item the spec does not keep, or a spec that gives its match tokens' order as a list of its own (Go's tokenOrder), whose rules' order, which ranks the tokens, is lost."
    ]
  }
}
`,
  render: Object.freeze({ entry: "gbnf-render", source: `; GBNF's render: a grammar-spec tree, the GrammarSpec the tabnas BNF
; compiler (tabnas-bnf) emits for a grammar, written back as llama.cpp
; GBNF. This is a library of definitions, each named \`gbnf-...\`, which a
; host links with its own program (alchemy's \`compile_sources\`); its entry
; point is \`gbnf-render\`, and nothing else here is the host's to call.
;
; A host reads a GBNF document by compiling it: the grammar-spec tree is
; the pure-data GrammarSpec that tabnas-bnf's \`compileSpec(gbnfConvert(src,
; {builtins: true}), {recognition: false, strict: true})\` writes
; (\`compile_spec\` over \`gbnf_convert\` in Rust, the same text; \`ToJsonic\`
; over \`ToPureSpec\` over \`Gbnf\` in Go, which writes its keys in name
; order), parsed as JSON. Its schema is \`grammar-spec\`, shared with ABNF
; and EBNF, whose compilers emit the same shape; the contract is the round
; trip: the text written here compiles back to the spec it was written
; from. This repository's \`render_gbnf\` (Rust, \`renderGbnf\` in
; TypeScript) writes GBNF from the IR a GBNF document parses to; this
; writes it from the spec the IR compiles to, and spells each terminal,
; group and repetition as that one does.
;
; The spec is a compiled grammar, not the grammar's text, so the render
; reads the compiler's shapes back into the notation:
;
; - A rule the author wrote is a rule of the spec that the spec's
;   \`meta.provenance\` does not name (a spec without it is read by the
;   names the compiler gives its rules, a helper's only where it has
;   the shape of its kind too, and the start wrapper by its shape);
;   every rule it names is the compiler's: a repetition's, an
;   option's or a group's helper (\`_gen<n>_star_...\`, \`_plus_\`, \`_opt_\`,
;   \`_rep_\`, \`_group\`), a sequence's chain steps (\`$alt<i>\`,
;   \`$step<j>\`), a left-factored tail (\`$fact<k>\`) and the start
;   wrapper. A helper is written where it is referenced, as the
;   construct it compiles: a repeat loop (the replace loop every \`x*\`
;   compiles to, its entry \`{c: {n.rep: 0}, r: <self>}\`) as \`x*\`, a plus
;   as \`x+\`, an option as \`x?\`, a counted repetition as \`x{m,n}\` (its
;   nested optionals counted), a group as \`(...)\`. A factored tail is
;   expanded back into the alternatives it was factored from, which the
;   compiler factors again, and alternatives that were each a group,
;   which the compiler factored into the first, are read back as the
;   groups they were.
; - An alternative of a rule is read from the alternates the compiler
;   emitted for it: a chain of steps, one per segment of terminals and a
;   reference; a dispatcher's \`$alt<i>\` rules, the gap in their numbers
;   the empty alternative; or, for a rule whose every alternative is one
;   segment, its open alternates, each read as the tokens it consumes
;   (its \`s\` less the \`b\` it gives back) and the rule it pushes, the
;   lookahead copies the dispatch made of one alternative read as one,
;   the empty alternative first (the compiler puts it last wherever it
;   stood), and those that push a helper in the order of the helpers'
;   numbers, which the compiler gives them before it reorders the
;   alternatives to tell them apart.
; - A leading reference the compiler substituted by the referenced rule's
;   alternatives is written back where those alternatives, each followed
;   by one same tail, still stand together.
; - A token is written as the terminal it matches: a fixed token as a
;   string, a class as \`[...]\` (a token set the compiler laid over a
;   contested class read back from its name, once its tokens are found
;   to be that class), \`[\\s\\S]\` as \`.\`; a string's and a class's
;   characters as \`render_gbnf\` spells them. A token named for a rule
;   the compiler lifted to it (\`plus ::= "+"\` becomes the token \`#plus\`)
;   is written as that rule, after the others, and referenced by name.
; - GBNF's start rule is \`root\`. A spec whose start rule has another name
;   is written with \`root ::= <start>\` first, as \`render_gbnf\` writes it.
;
; What a rule cannot be read back to is refused with
; TARGET_VALUE_UNREPRESENTABLE, naming the rule: an action other than
; the tree builders every compiled grammar carries (a value annotation's
; builders, a user action, the probe dispatcher's), a condition or a
; counter other than a repeat loop's, an error generator or an alternate
; modifier (\`e\`, \`h\`), a function reference where a rule or a count is
; due, a set of tokens at one place, the form that edits a rule already
; installed (\`{alts, inject}\`), a removal, and a token no GBNF terminal
; matches (the engine's own \`#TX\`, \`#NR\`, \`#ST\` and \`#VL\`, a class whose
; flags change what it matches, a pattern that is neither one class nor
; an escaped literal). A token set whose tokens are not the class its
; name gives, a rule with no alternate to open with, a sequence's step
; with more alternates than a step, and a rule the compiler lifted to a
; token whose name another rule holds are refused too. A spec serialized
; by Go, which writes its rules in name order and its match tokens'
; order as a list of its own (\`options.match.tokenOrder\`), is refused
; when that list holds two tokens or more: the rules' order, which ranks
; the tokens (the order the lexer tries two tokens a place expects), is
; lost. The tree builders and the marks are not written: the compiler
; makes them again from the rules.
;
; A spec compiled from another notation is written as far as GBNF can say
; it: a case-insensitive literal (ABNF's default) as the sequence of
; two-case classes and strings that matches exactly what it matches, as
; \`render_gbnf\` writes it, and an RFC 5234 core rule as a rule of its own.
;
; The whole spec is materialized before a line is written: a rule's
; alternatives are spread over its chain rules and helpers, which the
; spec keeps elsewhere in its \`rule\` object.

; ---- text and vectors

def gbnf-at [v i]
  get-path (as-path [i]) v

def gbnf-num [n]
  scalar-text csv-options n

def gbnf-empty [s]
  match s
    case "" true
    case _ false

def gbnf-full [s]
  match s
    case "" false
    case _ true

; Whether the strings a and b are the same: a string cut by itself is two
; empty strings, and by any other string it is not.
def gbnf-same [a b]
  match b
    case "" (gbnf-empty a)
    case _
      match (split b a)
        case ["" ""] true
        case _ false

def gbnf-not [x]
  match x
    case true false
    case false true

def gbnf-less [a b]
  match (compare a b)
    case :less true
    case _ false

def gbnf-some [v]
  match (count v)
    case 0 false
    case _ true

def gbnf-none [v]
  match (count v)
    case 0 true
    case _ false

def gbnf-rest [v]
  map (fn [i] (gbnf-at v i)) (filter (fn [i] (match i (case 0 false) (case _ true))) (indices v))

def gbnf-take [n v]
  map (fn [i] (gbnf-at v i)) (filter (fn [i] (gbnf-less i n)) (indices v))

def gbnf-drop [n v]
  map (fn [i] (gbnf-at v i)) (filter (fn [i] (gbnf-not (gbnf-less i n))) (indices v))

; Whether s begins with the non-empty p, ends with it; s after its first
; p, before its last.
def gbnf-starts [p s]
  match s
    case "" false
    case _ (gbnf-empty (gbnf-at (split p s) 0))

def gbnf-ends [p s]
  match s
    case "" false
    case _ (gbnf-empty (top (split p s)))

def gbnf-after [p s]
  string-join p (gbnf-rest (split p s))

def gbnf-before [p s]
  string-join p (pop (split p s))

def gbnf-digits [s]
  match s
    case "" false
    case _ (chars-within [[48 57]] s)

; The items of two vectors, and of a vector of vectors, in order: each
; item is named by its place, the places joined as text and read back.
def gbnf-cat [a b]
  gbnf-flat [a b]

def gbnf-flat [vv]
  map
    fn [t]
      let [p (split "." t)]
        get-path (as-path [(number (gbnf-at p 0)) (number (gbnf-at p 1))]) vv
    filter gbnf-full
      split ","
        string-join ","
          map
            fn [j]
              string-join "," (map (fn [i] (string-join "." [(gbnf-num j) (gbnf-num i)])) (indices (gbnf-at vv j)))
            indices vv

; Whether the string s is among the strings of v.
def gbnf-among [s v]
  gbnf-some (filter (fn [x] (gbnf-same x s)) v)

; The items of v whose key is the first of its kind, in order.
def gbnf-unique [keyf v]
  let [ks (map keyf v)]
    let [prev (gbnf-cat ["\\u0000"] (pop (gbnf-cat ks ["\\u0000"])))]
      let [runs (filter (fn [i] (gbnf-not (gbnf-same (gbnf-at ks i) (gbnf-at prev i)))) (indices ks))]
        map
          fn [i] (gbnf-at v i)
          filter
            fn [i]
              gbnf-none (filter (fn [j] (match (gbnf-less j i) (case true (gbnf-same (gbnf-at ks j) (gbnf-at ks i))) (case false false))) runs)
            runs

def gbnf-plus [a b]
  length (string-join "" [(repeat a "x") (repeat b "x")])

def gbnf-ones [n]
  pop (split "x" (repeat n "x"))

def gbnf-even [j]
  gbnf-some (filter (fn [d] (gbnf-ends d (gbnf-num j))) ["0" "2" "4" "6" "8"])

def gbnf-fail [what]
  fail :unrepresentable (string-join "" ["the grammar spec cannot be written as GBNF: " what])

; ---- the spec

def gbnf-rec [v]
  match (kind v)
    case :record v
    case _ (record)

def gbnf-vec [v]
  match (kind v)
    case :vector (as-vector v)
    case _ []

def gbnf-str [v]
  match (kind v)
    case :string v
    case _ ""

def gbnf-context [spec]
  let [o (gbnf-rec (get "options" spec))]
    record
      entry :rules (gbnf-rec (get "rule" spec))
      entry :fixed (gbnf-rec (get-path (as-path ["fixed" "token"]) o))
      entry :match (gbnf-rec (get-path (as-path ["match" "token"]) o))
      entry :sets (gbnf-rec (get "tokenSet" o))
      entry :prov (get-path (as-path ["meta" "provenance"]) spec)
      entry :start (gbnf-str (get-path (as-path ["rule" "start"]) o))

def gbnf-rule [cx name]
  get-path (as-path [name]) (get :rules cx)

def gbnf-has [cx name]
  match (kind (gbnf-rule cx name))
    case :record true
    case _ false

; A rule's alternates in one phase, the falsy placeholders the engine
; skips left out.
def gbnf-open [r]
  filter (fn [alt] (match (kind alt) (case :record true) (case _ false))) (gbnf-vec (get "open" r))

def gbnf-close [r]
  filter (fn [alt] (match (kind alt) (case :record true) (case _ false))) (gbnf-vec (get "close" r))

; The tokens an alternate matches: its \`s\`, a string of token names
; between spaces or a list of them.
def gbnf-s [alt]
  let [s (get "s" alt)]
    match (kind s)
      case :string (filter gbnf-full (split " " s))
      case :vector (map gbnf-str (as-vector s))
      case _ []

def gbnf-b [alt]
  match (kind (get "b" alt))
    case :number (get "b" alt)
    case _ 0

def gbnf-p [alt]
  gbnf-str (get "p" alt)

def gbnf-r [alt]
  gbnf-str (get "r" alt)

def gbnf-a [alt]
  match (kind (get "a" alt))
    case :string (get "a" alt)
    case :missing ""
    case :null ""
    case _ "?"

; Whether the compiler made the rule: provenance names every rule it
; synthesized, and a spec without provenance is read by the names it
; gives them.
def gbnf-made [cx name]
  match (kind (get :prov cx))
    case :record
      match (kind (get-path (as-path [name]) (get :prov cx)))
        case :string true
        case _ false
    case _
      match (gbnf-some (gbnf-rest (split "$" name)))
        case true (gbnf-split-name name)
        case false
          match (gbnf-gen-kind name)
            case ""
              match (gbnf-same name (get :start cx))
                case true (gbnf-wrapper (gbnf-rule cx name))
                case false false
            case k (gbnf-helper-shape cx name k)

; The kind of helper a name gives, as the compiler names the helpers it
; makes, \`_gen<n>_<kind>...\` with the kind a repetition's, an option's or
; a group's (\`_gen3_star_x\`, \`_gen4_group\`), or "" for any other name: a
; rule the author wrote may begin with \`_gen\` too (\`_general\`).
def gbnf-gen-kind [name]
  match (gbnf-starts "_gen" name)
    case false ""
    case true
      let [parts (split "_" (gbnf-after "_gen" name))]
        match (count parts)
          case 1 ""
          case _
            match (match (gbnf-digits (gbnf-at parts 0)) (case true (gbnf-among (gbnf-at parts 1) ["star" "plus" "opt" "rep" "group"])) (case false false))
              case true (gbnf-at parts 1)
              case false ""

; Whether a name is one the compiler gives a rule it splits off another,
; every part after a \`$\` one of its own: a dispatcher's alternative
; (\`$alt<i>\`), a chain's step (\`$step<j>\`), a left-factored tail
; (\`$fact<k>\`), a probe dispatcher (\`$pd<i>\`) and its parts (\`$probe\`,
; \`$with\`, \`$no\`, numbered where the name was taken).
def gbnf-split-name [name]
  gbnf-none (filter (fn [p] (gbnf-not (gbnf-split-part p))) (gbnf-rest (split "$" name)))

def gbnf-split-part [p]
  gbnf-some (filter (fn [k] (gbnf-split-fits k p)) ["alt" "step" "fact" "pd" "probe" "with" "no"])

def gbnf-split-fits [k p]
  match (gbnf-starts k p)
    case false false
    case true
      match (gbnf-after k p)
        case "" (gbnf-among k ["probe" "with" "no"])
        case rest (gbnf-digits rest)

; A rule named as the compiler names a helper, in a spec that names no
; provenance, is the compiler's where it has the shape the compiler gives
; that kind, and the author's otherwise: a repetition's loop has its
; guarded entry (\`{c: {n.rep: 0}, r: <self>}\`); a plus is its item and the
; loop after it; an option one element and the empty alternative; a
; counted repetition copies of one element, and the option or the loop
; after them; a group any alternatives.
def gbnf-helper-shape [cx name k]
  match k
    case "group" true
    case "star" (gbnf-some (filter (fn [alt] (gbnf-loop-entry name alt)) (gbnf-open (gbnf-rule cx name))))
    case _
      let [alts (gbnf-raw-alts cx name)]
        match k
          case "plus" (gbnf-plus-shape alts)
          case "opt" (gbnf-opt-shape alts)
          case _ (gbnf-rep-shape alts)

def gbnf-loop-entry [name alt]
  match (gbnf-same (gbnf-r alt) name)
    case false false
    case true
      let [c (get "c" alt)]
        match (kind c)
          case :record (gbnf-loop-value c "n.rep" [0])
          case _ false

def gbnf-plus-shape [alts]
  match (count alts)
    case 1
      let [seq (gbnf-vec (gbnf-at alts 0))]
        match (count seq)
          case 2 (gbnf-same (gbnf-helper-ref (gbnf-at seq 1)) "star")
          case _ false
    case _ false

def gbnf-opt-shape [alts]
  match (count alts)
    case 2
      let [counts (map count alts)]
        match (gbnf-among "0" (map gbnf-num counts))
          case true (gbnf-among "1" (map gbnf-num counts))
          case false false
    case _ false

def gbnf-rep-shape [alts]
  match (count alts)
    case 1
      let [seq (gbnf-vec (gbnf-at alts 0))]
        match (count seq)
          case 0 true
          case _
            let [lead (match (gbnf-among (gbnf-helper-ref (top seq)) ["star" "opt"]) (case true (pop seq)) (case false seq))]
              let [keys (map gbnf-el-name lead)]
                gbnf-none (filter (fn [key] (match key (case "" true) (case _ (gbnf-not (gbnf-same key (gbnf-at keys 0)))))) keys)
    case _ false

; The kind of helper an element references by name, or "".
def gbnf-helper-ref [el]
  match (get :k el)
    case :ref (gbnf-gen-kind (get :name el))
    case _ ""

; A token or a reference by its name, any other element "".
def gbnf-el-name [el]
  match (get :k el)
    case :tok (string-join "" ["#" (get :name el)])
    case :ref (string-join "" ["@" (get :name el)])
    case _ ""

; The start wrapper the compiler adds, which \`options.rule.start\` names:
; one open alternate that consumes nothing and pushes the grammar's start
; rule, and nothing but the end of the source to close it.
def gbnf-wrapper [r]
  let [o (gbnf-open r)]
    match (count o)
      case 1
        let [a (gbnf-at o 0)]
          match (match (gbnf-some (gbnf-s a)) (case true false) (case false (gbnf-full (gbnf-p a))))
            case false false
            case true (gbnf-none (filter (fn [c] (gbnf-not (gbnf-same (string-join " " (gbnf-s c)) "#ZZ"))) (gbnf-close r)))
      case _ false

; ---- what the spec may hold

; Every alternate is one the compiler's tree-building grammars are made
; of: the tokens it matches and gives back (\`s\`, \`b\`), the rule it pushes
; or replaces itself with (\`p\`, \`r\`), the tree builders (\`a\`, \`k\`), group
; tags, marks and per-rule scratch (\`g\`, \`m\`, \`u\`), and, in a repeat loop
; alone, the loop's guard and counter (\`c\`, \`n\`). Anything more is a
; construct the notation does not write: an error generator (\`e\`), an
; alternate modifier (\`h\`), a function in place of a rule or a count, an
; action other than the tree builders, another condition or counter.
def gbnf-alt-keys ["s" "b" "p" "r" "a" "c" "n" "k" "g" "m" "u"]

def gbnf-key-text [key]
  match key
    case "e" "e (an error generator)"
    case "h" "h (an alternate modifier)"
    case _ key

def gbnf-check-alt [cx name alt]
  let [extra (filter (fn [key] (match (gbnf-among key gbnf-alt-keys) (case true false) (case false (gbnf-given (get key alt))))) (keys alt))]
    match (count extra)
      case 0 (gbnf-check-parts cx name alt)
      case _ (gbnf-fail (string-join "" ["rule " name " has an alternate carrying " (string-join ", " (map gbnf-key-text extra)) ", which is not written"]))

def gbnf-check-parts [cx name alt]
  let [a (gbnf-a alt)]
    match (gbnf-among a ["" "@node$" "@capture$" "@bubble$" "@fold$"])
      case false
        match (gbnf-starts "@probe" (gbnf-action-text alt))
          case true (gbnf-fail (string-join "" ["rule " name " is the probe dispatcher the compiler makes for an optional prefix ([ X D ] Y), which is not read back"]))
          case false (gbnf-fail (string-join "" ["rule " name " carries an action (" (gbnf-action-text alt) "), which is not written"]))
      case true
        let [tokens (gbnf-check-s name (get "s" alt))]
          let [next (count (map (fn [key] (gbnf-check-next name key (get key alt))) ["p" "r"]))]
            let [back (gbnf-check-back name (get "b" alt))]
              gbnf-check-loop cx name alt

; The tokens: a string of names between spaces, or a list of names, one
; place each; a place holding a set of tokens (names between spaces, or a
; list) chooses among them, which the render does not read back.
def gbnf-check-s [name s]
  match (kind s)
    case :missing true
    case :null true
    case :string true
    case :vector
      match (gbnf-none (filter (fn [t] (match (kind t) (case :string (gbnf-some (gbnf-rest (split " " t)))) (case _ true))) (as-vector s)))
        case true true
        case false (gbnf-fail (string-join "" ["rule " name " has an alternate whose s holds, at one place, a set of tokens or something other than a token's name, which is not written"]))
    case _ (gbnf-fail (string-join "" ["rule " name " has an alternate whose s is not tokens, which is not written"]))

; The rule an alternate pushes or replaces itself with: a name, or none;
; a function reference (\`@name\`) chooses at run time and is not written.
def gbnf-check-next [name key v]
  match (kind v)
    case :missing true
    case :null true
    case :boolean (match v (case false true) (case _ (gbnf-fail (string-join "" ["rule " name " has an alternate whose " key " is not a rule, which is not written"]))))
    case :string
      match (gbnf-starts "@" v)
        case true (gbnf-fail (string-join "" ["rule " name " has an alternate whose " key " is the function reference " v ", which is not written"]))
        case false true
    case _ (gbnf-fail (string-join "" ["rule " name " has an alternate whose " key " is not a rule, which is not written"]))

def gbnf-check-back [name v]
  match (kind v)
    case :missing true
    case :null true
    case :number true
    case :boolean (match v (case false true) (case _ (gbnf-fail (string-join "" ["rule " name " has an alternate whose b is not a count, which is not written"]))))
    case _ (gbnf-fail (string-join "" ["rule " name " has an alternate whose b is not a count (" (gbnf-str v) "), which is not written"]))

; A repeat loop's guard (\`c: {n.rep: 0}\`) and counter (\`n: {rep: 0}\` or
; \`{rep: 1}\`), in the loop the compiler makes for a repetition and the
; steps of its item, and nowhere else.
def gbnf-loop-rule [cx name]
  gbnf-same (gbnf-helper-kind cx (gbnf-at (split "$" name) 0)) "star"

def gbnf-check-loop [cx name alt]
  let [c (get "c" alt)]
    let [n (get "n" alt)]
      match (match (gbnf-given c) (case true true) (case false (gbnf-given n)))
        case false true
        case true
          match (gbnf-loop-rule cx name)
            case false (gbnf-fail (string-join "" ["rule " name " carries a condition or a counter outside a repetition's loop, which is not written"]))
            case true
              match (match (gbnf-given c) (case false true) (case true (match (kind c) (case :record (gbnf-loop-value c "n.rep" [0])) (case _ false))))
                case false (gbnf-fail (string-join "" ["rule " name " carries a condition other than its loop's, which is not written"]))
                case true
                  match (match (gbnf-given n) (case false true) (case true (match (kind n) (case :record (gbnf-loop-value n "rep" [0 1])) (case _ false))))
                    case false (gbnf-fail (string-join "" ["rule " name " carries a counter other than its loop's, which is not written"]))
                    case true true

; Whether an alternate gives a field: the engine reads a field that is
; missing, null or false as one it does not give.
def gbnf-given [v]
  match (kind v)
    case :missing false
    case :null false
    case :boolean (match v (case false false) (case _ true))
    case _ true

def gbnf-loop-value [rec key allowed]
  match (keys rec)
    case [only]
      match (gbnf-same only key)
        case false false
        case true
          let [v (get-path (as-path [key]) rec)]
            gbnf-some (filter (fn [x] (match (compare v x) (case :equal true) (case _ false))) allowed)
    case _ false

def gbnf-action-text [alt]
  match (kind (get "a" alt))
    case :string (get "a" alt)
    case :vector (string-join " " (map gbnf-str (as-vector (get "a" alt))))
    case _ "a function"

; A rule's phases: a list of alternates each, or none; the form that edits
; a rule already installed (\`{alts, inject}\`) is not written.
def gbnf-check-phase [name phase v]
  match (kind v)
    case :missing true
    case :null true
    case :vector true
    case :record (gbnf-fail (string-join "" ["rule " name " gives its " phase " alternates as alts and an inject, which edits a rule already installed and is not written"]))
    case _ (gbnf-fail (string-join "" ["rule " name " gives its " phase " alternates in a form that is not a list, which is not written"]))

def gbnf-check-rule [cx name]
  let [r (gbnf-rule cx name)]
    match (kind r)
      case :record
        let [phases (count (map (fn [phase] (gbnf-check-phase name phase (get phase r))) ["open" "close"]))]
          match (count (gbnf-open r))
            case 0 (gbnf-fail (string-join "" ["rule " name " has no alternate to open with, which no grammar text writes"]))
            case _ (count (map (fn [alt] (gbnf-check-alt cx name alt)) (gbnf-cat (gbnf-open r) (gbnf-close r))))
      case :null (gbnf-fail (string-join "" ["rule " name " is removed, which is not written"]))
      case _ (gbnf-fail (string-join "" ["rule " name " is not a rule's alternates, which is not written"]))

; A spec serialized by Go writes its keys in name order and its match
; tokens' order in a list of its own (\`options.match.tokenOrder\`): the
; rules' order, which decides the order the compiler gives the tokens
; again, is lost, and with it which of two tokens that both match wins.
def gbnf-check-order [spec]
  let [order (get-path (as-path ["options" "match" "tokenOrder"]) spec)]
    match (kind order)
      case :vector
        match (gbnf-less (count (as-vector order)) 2)
          case true true
          case false (gbnf-fail "it gives its match tokens' order as a list of its own (tokenOrder, Go's serialization, whose keys are in name order), and the order of the rules, which their precedence follows, is lost")
      case _ true

def gbnf-check [spec cx]
  match (get "clear" spec)
    case true (gbnf-fail "it clears the grammar it is installed on, which is not written")
    case _
      let [order (gbnf-check-order spec)]
        let [rules (count (map (fn [name] (gbnf-check-rule cx name)) (keys (get :rules cx))))]
          gbnf-check-sets cx (gbnf-used cx)

; ---- tokens

def gbnf-bare [t]
  gbnf-after "#" t

def gbnf-lit [text cs]
  record
    entry :k :lit
    entry :text text
    entry :cs cs

def gbnf-class [pat flags]
  record
    entry :k :class
    entry :pat pat
    entry :flags flags

; A pattern's escapes taken back off: an escaped backslash is a pair, any
; other escape one backslash before the character it escapes.
def gbnf-unescape [s]
  string-join "\\\\" (map (fn [piece] (string-join "" (split "\\\\" piece))) (split "\\\\\\\\" s))

; A match token's source, \`@~/^.../flags\`: a class, or a case-folding
; literal.
def gbnf-match-token [t m]
  let [parts (split "/" m)]
    let [flags (top parts)]
      let [src (string-join "/" (pop (gbnf-rest parts)))]
        match (gbnf-starts "^" src)
          case false (gbnf-fail (string-join "" ["the token " t " is the pattern " m ", which no GBNF terminal matches"]))
          case true
            let [body (gbnf-after "^" src)]
              match (gbnf-starts "[" body)
                case true
                  match (gbnf-class-pattern body)
                    case false (gbnf-fail (string-join "" ["the token " t " is the pattern " m ", which is not one class the render reads, and no GBNF terminal matches it"]))
                    case true
                      match (gbnf-flags-fit body flags)
                        case true (gbnf-class body flags)
                        case false (gbnf-fail (string-join "" ["the token " t " is the class " m ", whose flags (" (match flags (case "" "none") (case _ flags)) ") change what it matches, and no GBNF terminal matches it"]))
                case false
                  match flags
                    case "i"
                      match (gbnf-escaped-literal body)
                        case true (gbnf-lit (gbnf-unescape body) false)
                        case false (gbnf-fail (string-join "" ["the token " t " is the pattern " m ", which is not a literal the render reads, and no GBNF terminal matches it"]))
                    case _ (gbnf-fail (string-join "" ["the token " t " is the pattern " m ", which no GBNF terminal matches"]))

; Whether a pattern's body is one class as the compiler writes one:
; \`[\`, an optional \`^\`, members each a \`\\uXXXX\` or \`\\u{X...}\` escape, alone
; or the low end of a range, and \`]\` ending it; or \`[\\s\\S]\`, which
; another notation's \`.\` compiles to.
def gbnf-class-pattern [body]
  match body
    case "[\\\\s\\\\S]" true
    case _
      match (gbnf-ends "]" body)
        case false false
        case true
          let [inner (gbnf-before "]" (gbnf-after "[" body))]
            match (gbnf-some (filter (fn [c] (gbnf-some (gbnf-rest (split c inner)))) ["[" "]"]))
              case true false
              case false
                let [pieces (split "\\\\u" (match (gbnf-starts "^" inner) (case true (gbnf-after "^" inner)) (case false inner)))]
                  match (gbnf-empty (gbnf-at pieces 0))
                    case false false
                    case true
                      let [members (gbnf-rest pieces)]
                        match (count members)
                          case 0 false
                          case _
                            match (gbnf-ends "-" (top members))
                              case true false
                              case false (gbnf-none (filter (fn [m] (gbnf-not (gbnf-member-piece m))) members))

def gbnf-member-piece [piece]
  let [core (match (gbnf-ends "-" piece) (case true (gbnf-before "-" piece)) (case false piece))]
    match (gbnf-starts "{" core)
      case true
        match (gbnf-ends "}" core)
          case false false
          case true
            let [h (gbnf-before "}" (gbnf-after "{" core))]
              match (gbnf-among (gbnf-num (length h)) ["1" "2" "3" "4" "5" "6"])
                case false false
                case true (gbnf-hex-only h)
      case false
        match (length core)
          case 4 (gbnf-hex-only core)
          case _ false

def gbnf-hex-only [h]
  match h
    case "" false
    case _ (chars-within [[48 57] [65 70] [97 102]] h)

; Whether a pattern's body is a literal as the compiler escapes one: every
; character a pattern reads otherwise (\`\\ ^ $ . * + ? ( ) [ ] { } |\`)
; after a backslash, and a backslash before nothing else.
def gbnf-meta-chars ["^" "$" "." "*" "+" "?" "(" ")" "[" "]" "{" "}" "|"]

def gbnf-escaped-literal [body]
  let [rest (gbnf-strip-escapes gbnf-strip-escapes gbnf-meta-chars (string-join "" (split "\\\\\\\\" body)))]
    match (gbnf-some (gbnf-rest (split "\\\\" rest)))
      case true false
      case false (gbnf-none (filter (fn [c] (gbnf-some (gbnf-rest (split c rest)))) gbnf-meta-chars))

def gbnf-strip-escapes [self cs s]
  match (count cs)
    case 0 s
    case _ (self self (pop cs) (string-join "" (split (string-join "" ["\\\\" (top cs)]) s)))

; A token set's class, read back from its name, which the compiler gives
; the class it lays over the atoms (\`rx_\` and the pattern, each character
; that is not a letter or a digit an underscore, in capitals). Each member
; of the pattern is a \`\\u\` escape, \`\\uXXXX\` or \`\\u{X...}\`, alone or the
; low end of a range; the name keeps their digits and order.
def gbnf-hex-lower [h]
  string-join "a" (split "A" (string-join "b" (split "B" (string-join "c" (split "C" (string-join "d" (split "D" (string-join "e" (split "E" (string-join "f" (split "F" h)))))))))))

def gbnf-hex-upper [h]
  string-join "A" (split "a" (string-join "B" (split "b" (string-join "C" (split "c" (string-join "D" (split "d" (string-join "E" (split "e" (string-join "F" (split "f" h)))))))))))

def gbnf-set-member [piece]
  let [parts (split "_" piece)]
    match (gbnf-empty (gbnf-at parts 0))
      case true
        record
          entry :text (string-join "" ["\\\\u{" (gbnf-hex-lower (gbnf-at parts 1)) "}"])
          entry :braced true
          entry :range (match (count parts) (case 4 true) (case _ false))
      case false
        record
          entry :text (string-join "" ["\\\\u" (gbnf-hex-lower (gbnf-at parts 0))])
          entry :braced false
          entry :range (match (count parts) (case 2 true) (case _ false))

def gbnf-set-token [t]
  let [rest (gbnf-after "RX_" (gbnf-bare t))]
    match rest
      case "__S_S" (gbnf-class "[\\\\s\\\\S]" "u")
      case _
        let [pieces (split "_U" rest)]
          let [members (map gbnf-set-member (gbnf-rest pieces))]
            let [negated (gbnf-same (gbnf-at pieces 0) "__")]
              let [body (string-join "" (map (fn [m] (string-join "" [(get :text m) (match (get :range m) (case true "-") (case false ""))])) members))]
                let [pat (string-join "" ["[" (match negated (case true "^") (case false "")) body "]"])]
                  match (gbnf-same (gbnf-class-name pat) (gbnf-bare t))
                    case false (gbnf-fail (string-join "" ["the token set " t " names no class the render can read back"]))
                    case true
                      match negated
                        case true (gbnf-class pat "u")
                        case false (gbnf-class pat (match (gbnf-some (filter (fn [m] (get :braced m)) members)) (case true "u") (case false "")))

; The name the compiler gives a class's token: \`rx_\` and its pattern, every
; character but a letter or a digit an underscore, in capitals, with the
; underscores at the end taken off.
def gbnf-class-name [pat]
  let [u (gbnf-hex-upper (string-join "U" (split "u" (string-join "S" (split "s" pat)))))]
    let [n (string-join "_" (split "[" (string-join "_" (split "]" (string-join "_" (split "^" (string-join "_" (split "-" (string-join "_" (split "\\\\" (string-join "_" (split "{" (string-join "_" (split "}" u))))))))))))))]
      gbnf-trim-end (string-join "" ["RX_" n])

def gbnf-trim-end [s]
  match (gbnf-ends "_" s)
    case true (gbnf-trim-end-once (gbnf-before "_" s))
    case false s

def gbnf-trim-end-once [s]
  match (gbnf-ends "_" s)
    case true (gbnf-before "_" s)
    case false s

; ---- code points and the ranges a class holds

; A code point, from its one to six hexadecimal digits in either case, as
; three numbers, its bytes from the highest, each the place of its two
; digits among \`gbnf-hex-pairs\`: code points are ordered as these are.
def gbnf-cp [h]
  let [x (gbnf-six (gbnf-hex-upper h))]
    let [high (gbnf-pair-start x)]
      let [rest (gbnf-after high x)]
        vector (gbnf-pair-index high) (gbnf-pair-index (gbnf-pair-start rest)) (gbnf-pair-index (gbnf-pair-end rest))

def gbnf-six [h]
  string-join "" [(match (length h) (case 1 "00000") (case 2 "0000") (case 3 "000") (case 4 "00") (case 5 "0") (case _ "")) h]

def gbnf-pair-start [x]
  gbnf-at (filter (fn [p] (gbnf-starts p x)) gbnf-hex-pairs) 0

def gbnf-pair-end [x]
  gbnf-at (filter (fn [p] (gbnf-ends p x)) gbnf-hex-pairs) 0

def gbnf-pair-index [p]
  gbnf-at (filter (fn [i] (gbnf-same (gbnf-at gbnf-hex-pairs i) p)) (indices gbnf-hex-pairs)) 0

def gbnf-cp-order [a b]
  match (compare (gbnf-at a 0) (gbnf-at b 0))
    case :equal
      match (compare (gbnf-at a 1) (gbnf-at b 1))
        case :equal (compare (gbnf-at a 2) (gbnf-at b 2))
        case other other
    case other other

def gbnf-cp-before [a b]
  match (gbnf-cp-order a b)
    case :less true
    case _ false

def gbnf-cp-is [a b]
  match (gbnf-cp-order a b)
    case :equal true
    case _ false

; The code point after one: its low byte one more, carried into the bytes
; above it.
def gbnf-cp-next [c]
  match (gbnf-at c 2)
    case 255
      match (gbnf-at c 1)
        case 255 (vector (gbnf-plus (gbnf-at c 0) 1) 0 0)
        case _ (vector (gbnf-at c 0) (gbnf-plus (gbnf-at c 1) 1) 0)
    case _ (vector (gbnf-at c 0) (gbnf-at c 1) (gbnf-plus (gbnf-at c 2) 1))

def gbnf-cp-max [cps]
  gbnf-at (filter (fn [c] (gbnf-none (filter (fn [d] (gbnf-cp-before c d)) cps))) cps) 0

def gbnf-span [lo hi]
  record
    entry :lo lo
    entry :hi hi

; The members of a class's pattern, read as \`gbnf-class-pattern\` admits
; them: each a range, from its low end's digits to its high end's (a
; character alone is a range of one); \`[\\s\\S]\` every code point. A
; negated class's are the ones it excludes.
def gbnf-class-hex-spans [body]
  match body
    case "[\\\\s\\\\S]" [(gbnf-span "0" "10FFFF")]
    case _
      let [inner (gbnf-before "]" (gbnf-after "[" body))]
        let [pieces (gbnf-rest (split "\\\\u" (match (gbnf-starts "^" inner) (case true (gbnf-after "^" inner)) (case false inner))))]
          let [lows (map (fn [p] (gbnf-ends "-" p)) pieces)]
            let [ends (gbnf-cat [false] lows)]
              map
                fn [i]
                  let [lo (gbnf-piece-hex (gbnf-at pieces i))]
                    match (gbnf-at lows i)
                      case true (gbnf-span lo (gbnf-piece-hex (gbnf-at pieces (gbnf-plus i 1))))
                      case false (gbnf-span lo lo)
                filter (fn [i] (gbnf-not (gbnf-at ends i))) (indices pieces)

def gbnf-piece-hex [p]
  let [core (match (gbnf-ends "-" p) (case true (gbnf-before "-" p)) (case false p))]
    match (gbnf-starts "{" core)
      case true (gbnf-before "}" (gbnf-after "{" core))
      case false core

def gbnf-class-spans [body]
  map (fn [s] (gbnf-span (gbnf-cp (get :lo s)) (gbnf-cp (get :hi s)))) (gbnf-class-hex-spans body)

; Ranges sorted by their low ends and merged where they overlap or meet:
; two lists of ranges hold the same code points when these are the same.
def gbnf-spans-merged [spans]
  let [sorted (gbnf-spans-sorted spans)]
    let [starts (filter (fn [i] (gbnf-none (filter (fn [j] (match (gbnf-less j i) (case true (gbnf-not (gbnf-cp-before (gbnf-cp-next (get :hi (gbnf-at sorted j))) (get :lo (gbnf-at sorted i))))) (case false false))) (indices sorted)))) (indices sorted))]
      map (fn [k] (gbnf-block-span sorted starts k)) (indices starts)

def gbnf-block-span [sorted starts k]
  let [from (gbnf-at starts k)]
    let [members (filter (fn [i] (match (gbnf-less i from) (case true false) (case false (gbnf-before-start starts k i)))) (indices sorted))]
      gbnf-span (get :lo (gbnf-at sorted from)) (gbnf-cp-max (map (fn [i] (get :hi (gbnf-at sorted i))) members))

def gbnf-before-start [starts k i]
  match (gbnf-less (gbnf-plus k 1) (count starts))
    case true (gbnf-less i (gbnf-at starts (gbnf-plus k 1)))
    case false true

def gbnf-spans-sorted [spans]
  let [ranks (map (fn [i] (count (filter (fn [j] (match (gbnf-cp-order (get :lo (gbnf-at spans j)) (get :lo (gbnf-at spans i))) (case :less true) (case :equal (gbnf-less j i)) (case _ false))) (indices spans)))) (indices spans))]
    map (fn [k] (gbnf-at spans (gbnf-at (filter (fn [i] (match (compare (gbnf-at ranks i) k) (case :equal true) (case _ false))) (indices spans)) 0))) (indices spans)

def gbnf-spans-same [a b]
  match (compare (count a) (count b))
    case :equal (gbnf-none (filter (fn [i] (match (gbnf-cp-is (get :lo (gbnf-at a i)) (get :lo (gbnf-at b i))) (case true (gbnf-not (gbnf-cp-is (get :hi (gbnf-at a i)) (get :hi (gbnf-at b i))))) (case false true))) (indices a)))
    case _ false

; Whether two lists of ranges hold every code point between them, each
; once: a negated class's ranges and the ranges it matches.
def gbnf-spans-tile [a b]
  let [all (gbnf-spans-sorted (gbnf-cat (gbnf-spans-merged a) (gbnf-spans-merged b)))]
    match (count all)
      case 0 false
      case _
        match (match (gbnf-cp-is (get :lo (gbnf-at all 0)) (gbnf-cp "0")) (case true (gbnf-cp-is (get :hi (top all)) (gbnf-cp "10FFFF"))) (case false false))
          case false false
          case true
            let [nexts (gbnf-rest all)]
              gbnf-none (filter (fn [i] (gbnf-not (gbnf-cp-is (get :lo (gbnf-at nexts i)) (gbnf-cp-next (get :hi (gbnf-at all i)))))) (indices nexts))

; Whether a class's flags are the ones it is matched with once its text is
; written and compiled back. Every compiler here gives \`u\` to a class that
; is negated, holds a character past U+FFFF or is \`[\\s\\S]\`, and to no
; other. Without \`u\` such a class matches one UTF-16 code unit, half of a
; character past U+FFFF, and with it one code point. A class of other
; characters matches the same either way, unless it holds a surrogate,
; which \`u\` matches only where it stands alone.
def gbnf-flags-fit [body flags]
  match (gbnf-wants-u body)
    case true (gbnf-same flags "u")
    case false
      match (gbnf-holds-surrogate body)
        case true (gbnf-empty flags)
        case false (gbnf-among flags ["" "u"])

def gbnf-wants-u [body]
  match body
    case "[\\\\s\\\\S]" true
    case _
      match (gbnf-starts "[^" body)
        case true true
        case false (gbnf-some (gbnf-rest (split "\\\\u{" body)))

; A class none of whose members is past U+FFFF holds a surrogate where a
; range's low end is not above U+DFFF and its high end not below U+D800.
def gbnf-holds-surrogate [body]
  gbnf-some (filter (fn [s] (match (gbnf-hex-from (get :lo s) ["E" "F"]) (case true false) (case false (gbnf-hex-from (get :hi s) ["D8" "D9" "DA" "DB" "DC" "DD" "DE" "DF" "E" "F"])))) (gbnf-class-hex-spans body))

def gbnf-hex-from [h prefixes]
  let [x (gbnf-hex-upper h)]
    match (length x)
      case 4 (gbnf-some (filter (fn [p] (gbnf-starts p x)) prefixes))
      case _ false

; A token set is the class its name gives when the tokens it lays over
; that class are the class: their ranges, merged, are the class's ranges,
; or, for a negated class, every code point the class does not exclude.
; The compiler lays a contested class over the atoms of a partition, each
; a token of its own, and names the set for the class; the render writes
; the class the name gives, so a set whose tokens match anything else is
; refused.
def gbnf-check-sets [cx used]
  count (map (fn [k] (gbnf-check-set cx (string-join "" ["#" k]))) (filter (fn [k] (match (gbnf-starts "RX_" k) (case true (gbnf-some (gbnf-rest (split (string-join "" [" #" k " "]) used)))) (case false false))) (keys (get :sets cx))))

def gbnf-check-set [cx t]
  let [cls (gbnf-set-token t)]
    let [pat (get :pat cls)]
      let [spans (gbnf-flat (map (fn [m] (gbnf-member-spans cx t m)) (gbnf-vec (get-path (as-path [(gbnf-bare t)]) (get :sets cx)))))]
        let [own (gbnf-class-spans pat)]
          match (match (gbnf-starts "[^" pat) (case true (gbnf-spans-tile own spans)) (case false (gbnf-spans-same (gbnf-spans-merged own) (gbnf-spans-merged spans))))
            case true true
            case false (gbnf-fail (string-join "" ["the token set " t " lays tokens over its class " pat " that match other characters than the class does, and the render writes the class the set's name gives"]))

def gbnf-member-spans [cx t m]
  let [src (match (kind m) (case :string (gbnf-str (get-path (as-path [m]) (get :match cx)))) (case _ ""))]
    let [body (gbnf-after "^" (string-join "/" (pop (gbnf-rest (split "/" src)))))]
      match (match (gbnf-starts "@" src) (case true (match (gbnf-class-pattern body) (case true (match (gbnf-starts "[^" body) (case true false) (case false (gbnf-flags-fit body (top (split "/" src)))))) (case false false))) (case false false))
        case true (gbnf-class-spans body)
        case false (gbnf-fail (string-join "" ["the token set " t " holds " (gbnf-str m) ", which is not one class the render reads"]))

def gbnf-engine-token [t]
  match t
    case "#TX" (record (entry :k :engine) (entry :name "TX"))
    case "#NR" (record (entry :k :engine) (entry :name "NR"))
    case "#ST" (record (entry :k :engine) (entry :name "ST"))
    case "#VL" (record (entry :k :engine) (entry :name "VL"))
    case _ (gbnf-fail (string-join "" ["the token " t " is defined nowhere in the spec"]))

def gbnf-token [cx t]
  let [f (get-path (as-path [t]) (get :fixed cx))]
    match (kind f)
      case :string (gbnf-lit f true)
      case _
        let [m (get-path (as-path [t]) (get :match cx))]
          match (kind m)
            case :string (gbnf-match-token t m)
            case _
              match (kind (get-path (as-path [(gbnf-bare t)]) (get :sets cx)))
                case :vector (gbnf-set-token t)
                case _ (gbnf-engine-token t)

; ---- reading a rule's alternatives

; An element of an alternative as the spec holds it: a token, or a
; reference to a rule (the compiler's helpers among them).
def gbnf-tok-el [t]
  record
    entry :k :tok
    entry :name t

def gbnf-ref-el [n]
  record
    entry :k :ref
    entry :name n

; The tokens an alternate consumes, and the rule it hands over to.
def gbnf-consumed [alt]
  let [s (gbnf-s alt)]
    let [b (gbnf-b alt)]
      gbnf-take (count (filter (fn [j] (gbnf-not (gbnf-less j b))) (indices s))) s

def gbnf-target [alt]
  match (gbnf-p alt)
    case "" (gbnf-r alt)
    case p p

def gbnf-entry-els [alt]
  let [toks (map gbnf-tok-el (gbnf-consumed alt))]
    match (gbnf-target alt)
      case "" toks
      case to (push (gbnf-ref-el to) toks)

def gbnf-entry-key [alt]
  string-join "" [(string-join " " (gbnf-consumed alt)) "|" (gbnf-target alt)]

; A rule whose alternatives are each one segment: its open alternates,
; each read as what it consumes and pushes, a dispatch's lookahead copies
; of one alternative read as one; the empty alternative first, which the
; compiler puts last wherever it stood, so that either place compiles
; back the same. An alternate that consumes nothing and pushes nothing is
; the empty alternative, or a guard that ends it on what may follow; two
; or more bare ones (\`a ::= | \`) are as many empty alternatives.
def gbnf-simple-alts [r]
  let [alts (gbnf-flat (map (fn [alt] (map (fn [i] (gbnf-entry-els alt)) (indices (gbnf-ones (gbnf-copies (gbnf-open r) alt))))) (gbnf-unique gbnf-entry-key (gbnf-open r))))]
    let [bare (count (filter gbnf-bare-empty (gbnf-open r)))]
      let [empties (match (gbnf-some (filter gbnf-none alts)) (case false []) (case true (map (fn [i] []) (indices (gbnf-ones (match (gbnf-less bare 2) (case true 1) (case false bare)))))))]
        gbnf-cat empties (gbnf-number-order (filter gbnf-some alts))

; How many times an alternative stands among the open alternates: the
; lookahead copies a dispatch makes of one alternative consume and push the
; same and look ahead at different tokens, and are one; alternates alike
; in everything are as many alternatives as there are of them.
def gbnf-copies [open alt]
  let [group (filter (fn [a] (gbnf-same (gbnf-entry-key a) (gbnf-entry-key alt))) open)]
    let [counts (map (fn [a] (count (filter (fn [b] (gbnf-same (gbnf-whole-key b) (gbnf-whole-key a))) group))) group)]
      gbnf-at (filter (fn [c] (gbnf-none (filter (fn [d] (gbnf-less c d)) counts))) counts) 0

def gbnf-whole-key [alt]
  string-join "" [(string-join " " (gbnf-s alt)) "|" (gbnf-num (gbnf-b alt)) "|" (gbnf-target alt)]

def gbnf-bare-empty [alt]
  match (gbnf-some (gbnf-s alt))
    case true false
    case false (gbnf-empty (gbnf-target alt))

; The compiler reorders a rule's alternatives to tell them apart (a
; longer lookahead first, a keyword ahead of a class that takes it), and
; numbers the helpers it makes for them, in the order the alternatives
; were written, before it does. So the alternatives that push a helper
; are put back in the order of the helpers' numbers, among their own
; places; the others keep theirs.
def gbnf-alt-number [alt]
  match (count alt)
    case 0 -1
    case _
      let [last (top alt)]
        match (get :k last)
          case :ref
            match (gbnf-starts "_gen" (get :name last))
              case true
                let [d (gbnf-at (split "_" (gbnf-after "_gen" (get :name last))) 0)]
                  match (gbnf-digits d)
                    case true (number d)
                    case false -1
              case false -1
          case _ -1

def gbnf-number-order [alts]
  let [nums (map gbnf-alt-number alts)]
    let [slots (filter (fn [i] (gbnf-not (gbnf-less (gbnf-at nums i) 0))) (indices alts))]
      let [rank (fn [i] (count (filter (fn [j] (match (compare (gbnf-at nums j) (gbnf-at nums i)) (case :less true) (case :equal (gbnf-less j i)) (case _ false))) slots)))]
        let [ranks (map rank slots)]
          map (fn [i] (gbnf-number-at alts nums slots ranks i)) (indices alts)

def gbnf-number-at [alts nums slots ranks i]
  match (gbnf-less (gbnf-at nums i) 0)
    case true (gbnf-at alts i)
    case false
      let [k (count (filter (fn [j] (gbnf-less j i)) slots))]
        gbnf-at alts (gbnf-at slots (gbnf-at (filter (fn [m] (match (compare (gbnf-at ranks m) k) (case :equal true) (case _ false))) (indices slots)) 0))

; The first alternative that is not empty: an option's.
def gbnf-filled [alts]
  gbnf-at (filter gbnf-some alts) 0

; The steps of a chain, each a segment: the tokens its open alternate
; consumes and the rule it pushes, the next step named in its close.
def gbnf-chain-walk [self cx name depth acc]
  let [r (gbnf-chain-step name (gbnf-rule cx name))]
    let [els (gbnf-cat acc (gbnf-entry-els (gbnf-at (gbnf-open r) 0)))]
      match (count (gbnf-close r))
        case 0 els
        case _
          match (gbnf-r (gbnf-at (gbnf-close r) 0))
            case "" els
            case next
              match (gbnf-less (count depth) 200)
                case false (gbnf-fail (string-join "" ["rule " name " is a sequence of more than 200 segments, which the render does not follow"]))
                case true (self self cx next (push 1 depth) els)

def gbnf-chain [cx name]
  gbnf-chain-walk gbnf-chain-walk cx name [] []

; A dispatcher's alternatives: one rule per alternative, \`<rule>$alt<i>\`,
; and the empty one where a number is missing, or last.
def gbnf-head-name [name i]
  string-join "" [name "$alt" (gbnf-num i)]

def gbnf-dispatch-alts [cx name r]
  let [nums (indices (push 0 (gbnf-open r)))]
    let [present (filter (fn [i] (gbnf-has cx (gbnf-head-name name i))) nums)]
      let [last (top present)]
        let [gaps (filter (fn [i] (match (gbnf-less i last) (case true (gbnf-not (gbnf-among (gbnf-num i) (map gbnf-num present)))) (case false false))) nums)]
          let [empty (gbnf-some (filter (fn [alt] (gbnf-empty (gbnf-target alt))) (gbnf-open r)))]
            match (count gaps)
              case 0
                gbnf-cat (map (fn [i] (gbnf-chain cx (gbnf-head-name name i))) present) (match empty (case true [[]]) (case false []))
              case 1
                map
                  fn [i]
                    match (gbnf-has cx (gbnf-head-name name i))
                      case true (gbnf-chain cx (gbnf-head-name name i))
                      case false []
                  filter (fn [i] (gbnf-not (gbnf-less last i))) nums
              case _ (gbnf-fail (string-join "" ["rule " name " dispatches to alternatives the render cannot place"]))

; Whether the rule dispatches to \`$alt\` rules of its own.
def gbnf-dispatches [cx name r]
  gbnf-some (filter (fn [alt] (gbnf-starts (string-join "" [name "$alt"]) (gbnf-target alt))) (gbnf-open r))

; A loop's item: what its continue alternate takes, a token it consumes,
; or the rule its iteration (\`<loop>$alt0\`) pushes.
def gbnf-loop-item [cx name r]
  let [conts (filter (fn [alt] (gbnf-full (gbnf-r alt))) (gbnf-rest (gbnf-open r)))]
    match (count conts)
      case 0 (gbnf-fail (string-join "" ["the repetition " name " repeats nothing"]))
      case _
        let [c (gbnf-at conts 0)]
          match (gbnf-same (gbnf-r c) name)
            case true
              match (gbnf-consumed c)
                case [t] (gbnf-tok-el t)
                case _ (gbnf-fail (string-join "" ["the repetition " name " repeats more than one token"]))
            case false
              match (gbnf-p (gbnf-at (gbnf-open (gbnf-rule cx (gbnf-r c))) 0))
                case "" (gbnf-fail (string-join "" ["the repetition " name " repeats nothing"]))
                case item (gbnf-ref-el item)

; A tail repeat, \`X = prefix [ sep X ]\`, which the compiler makes a loop
; in the rule's close: the separator matched and the rule replaced.
def gbnf-is-tail [name r]
  match (count (gbnf-close r))
    case 2
      let [c (gbnf-at (gbnf-close r) 0)]
        match (gbnf-a c)
          case "@fold$" (gbnf-same (gbnf-r c) name)
          case _ false
    case _ false

; The alternatives of a rule as the spec holds them, each a vector of
; elements; a tail repeat as its prefix and the option around its
; separator and itself.
def gbnf-raw-alts [cx name]
  let [r (gbnf-rule cx name)]
    match (gbnf-is-tail name r)
      case true
        let [prefix (map gbnf-tok-el (gbnf-consumed (gbnf-at (gbnf-open r) 0)))]
          let [sep (map gbnf-tok-el (gbnf-consumed (gbnf-at (gbnf-close r) 0)))]
            vector
              push
                record
                  entry :k :tail
                  entry :seq (push (gbnf-ref-el name) sep)
                prefix
      case false
        match (gbnf-dispatches cx name r)
          case true (gbnf-dispatch-alts cx name r)
          case false
            match (count (gbnf-close r))
              case 0 (gbnf-simple-alts r)
              case _
                match (gbnf-r (gbnf-at (gbnf-close r) 0))
                  case "" (gbnf-simple-alts r)
                  case _ (vector (gbnf-chain cx name))

; A step of a sequence's chain, as the compiler makes one: one open
; alternate, a segment of the sequence, and at most one close alternate,
; which names the next step. A rule that replaces itself in its close and
; has more alternates than that is no chain the render reads back.
def gbnf-chain-step [name r]
  match (match (count (gbnf-open r)) (case 1 (gbnf-less (count (gbnf-close r)) 2)) (case _ false))
    case true r
    case false (gbnf-fail (string-join "" ["rule " name " replaces itself in its close as a sequence's step does, and has more alternates than a step, which is not read back"]))

; ---- the compiler's helpers, read back

; The kind of a helper the compiler named: \`_gen<n>_<kind>...\`.
def gbnf-helper-kind [cx name]
  match (gbnf-made cx name)
    case false ""
    case true
      match (gbnf-starts "_gen" name)
        case true
          let [parts (split "_" (gbnf-after "_gen" name))]
            match (gbnf-digits (gbnf-at parts 0))
              case true (gbnf-at parts 1)
              case false ""
        case false
          match (gbnf-among "fact" (map (fn [p] (gbnf-before-digits p)) (gbnf-rest (split "$" name))))
            case true "fact"
            case false ""

def gbnf-before-digits [p]
  match (gbnf-starts "fact" p)
    case true (match (gbnf-digits (gbnf-after "fact" p)) (case true "fact") (case false p))
    case false p

; An alternative with its factored tails expanded back: one whose last
; element is a left-factored tail (\`<rule>$fact<k>\`) is the prefix before
; it followed by each of the tail's alternatives in turn.
def gbnf-expand [self cx alt]
  match (count alt)
    case 0 [alt]
    case _
      let [last (top alt)]
        match (get :k last)
          case :ref
            match (gbnf-helper-kind cx (get :name last))
              case "fact"
                let [prefix (pop alt)]
                  gbnf-flat (map (fn [tail] (self self cx (gbnf-cat prefix tail))) (gbnf-raw-alts cx (get :name last)))
              case _ [alt]
          case _ [alt]

def gbnf-alts [cx name]
  gbnf-flat (map (fn [alt] (gbnf-split-group cx name alt)) (gbnf-flat (map (fn [alt] (gbnf-expand gbnf-expand cx alt)) (gbnf-raw-alts cx name))))

; The compiler factors a rule's alternatives that are each one group
; (\`( A x ) | ( A y )\`) into the first group, whose sequence then ends in
; the rule's own factored tail (\`<rule>$fact<k>\`); such an alternative is
; read back as the groups it was, one alternative each.
def gbnf-split-group [cx name alt]
  match (count alt)
    case 1
      let [el (gbnf-at alt 0)]
        match (get :k el)
          case :ref
            match (gbnf-helper-kind cx (get :name el))
              case "group"
                let [inner (gbnf-raw-alts cx (get :name el))]
                  match (count inner)
                    case 1
                      let [seq (gbnf-at inner 0)]
                        match (gbnf-owned-fact cx name seq)
                          case true (map (fn [one] [(gbnf-grp-el one)]) (gbnf-expand gbnf-expand cx seq))
                          case false [alt]
                    case _ [alt]
              case _ [alt]
          case _ [alt]
    case _ [alt]

def gbnf-owned-fact [cx name seq]
  match (count seq)
    case 0 false
    case _
      let [last (top seq)]
        match (get :k last)
          case :ref
            match (gbnf-helper-kind cx (get :name last))
              case "fact" (gbnf-starts (string-join "" [name "$fact"]) (get :name last))
              case _ false
          case _ false

; A group read back from a factored alternative: an element of its own,
; written as a group is.
def gbnf-grp-el [seq]
  record
    entry :k :grp
    entry :seq seq

; The parts a repetition counts: the item, how many at least, how many
; at most ("" for no bound). A bounded one ends in nested options, each
; over a group of the item and the next option, the innermost over the
; item alone: \`[ A [ A [ A ] ] ]\`. The compiler numbers them as it makes
; them, the innermost group first, under the number it gave the
; repetition: group n, option n+1 over it, group n+2, ..., so the
; outermost option's number says how deep they go.
def gbnf-gen-number [name]
  number (gbnf-at (split "_" (gbnf-after "_gen" name)) 0)

def gbnf-rep-chain [cx rep opt]
  let [n (gbnf-gen-number rep)]
    let [inner-name (string-join "" ["_gen" (gbnf-num n) "_group"])]
      match (gbnf-has cx inner-name)
        case false (gbnf-fail (string-join "" ["the repetition " rep " is not numbered as the compiler numbers one"]))
        case true
          let [inner (gbnf-raw-alts cx inner-name)]
            match (count (gbnf-at inner 0))
              case 1
                let [span (count (filter (fn [j] (gbnf-not (gbnf-less j n))) (indices (gbnf-ones (gbnf-plus (gbnf-gen-number opt) 1)))))]
                  record
                    entry :item (gbnf-at (gbnf-at inner 0) 0)
                    entry :depth (count (filter gbnf-even (indices (gbnf-ones span))))
              case _ (gbnf-fail (string-join "" ["the repetition " rep " is not numbered as the compiler numbers one"]))

def gbnf-rep-parts [cx name]
  let [seq (gbnf-at (gbnf-raw-alts cx name) 0)]
    let [last (match (count seq) (case 0 (gbnf-fail (string-join "" ["the repetition " name " repeats its item no times, and the spec does not keep the item"]))) (case _ (top seq)))]
      let [lead (pop seq)]
        match (gbnf-helper-kind cx (gbnf-str (get :name last)))
          case "star"
            record
              entry :item (gbnf-loop-item cx (get :name last) (gbnf-rule cx (get :name last)))
              entry :min (count lead)
              entry :max ""
          case "opt"
            let [chain (gbnf-rep-chain cx name (get :name last))]
              record
                entry :item (get :item chain)
                entry :min (count lead)
                entry :max (gbnf-num (gbnf-plus (count lead) (get :depth chain)))
          case _
            record
              entry :item (gbnf-at seq 0)
              entry :min (count seq)
              entry :max (gbnf-num (count seq))

; An element's structure as one string, a helper by what it compiles (a
; counted repetition by its item and counts, not by the nested options
; it compiles to, which are as deep as its count).
def gbnf-key [self cx el]
  match (get :k el)
    case :tok (get :name el)
    case :tail "[tail]"
    case :grp (string-join "" ["group(" (gbnf-key-seq self cx (get :seq el)) ")"])
    case :ref
      let [name (get :name el)]
        match (gbnf-helper-kind cx name)
          case "" (string-join "" ["@" name])
          case "star" (string-join "" ["*(" (self self cx (gbnf-loop-item cx name (gbnf-rule cx name))) ")"])
          case "rep"
            let [parts (gbnf-rep-parts cx name)]
              string-join "" ["rep(" (gbnf-num (get :min parts)) "," (get :max parts) "," (self self cx (get :item parts)) ")"]
          case kind (string-join "" [kind "(" (string-join "|" (map (fn [seq] (gbnf-key-seq self cx seq)) (gbnf-alts cx name))) ")"])

def gbnf-key-seq [self cx seq]
  string-join " " (map (fn [e] (self self cx e)) seq)

def gbnf-seq-keys [cx seq]
  map (fn [el] (gbnf-key gbnf-key cx el)) seq

; ---- characters

; A literal's characters as their code points, which a notation writes
; where a quoted string cannot hold a character, and the names the
; compiler derives from a literal's text.

; The ASCII characters, each with its two hexadecimal digits.
def gbnf-ascii [["\\u0000" "00"] ["\\u0001" "01"] ["\\u0002" "02"] ["\\u0003" "03"] ["\\u0004" "04"] ["\\u0005" "05"] ["\\u0006" "06"] ["\\u0007" "07"] ["\\b" "08"] ["\\t" "09"] ["\\n" "0A"] ["\\u000b" "0B"] ["\\f" "0C"] ["\\r" "0D"] ["\\u000e" "0E"] ["\\u000f" "0F"] ["\\u0010" "10"] ["\\u0011" "11"] ["\\u0012" "12"] ["\\u0013" "13"] ["\\u0014" "14"] ["\\u0015" "15"] ["\\u0016" "16"] ["\\u0017" "17"] ["\\u0018" "18"] ["\\u0019" "19"] ["\\u001a" "1A"] ["\\u001b" "1B"] ["\\u001c" "1C"] ["\\u001d" "1D"] ["\\u001e" "1E"] ["\\u001f" "1F"] [" " "20"] ["!" "21"] ["\\"" "22"] ["#" "23"] ["$" "24"] ["%" "25"] ["&" "26"] ["'" "27"] ["(" "28"] [")" "29"] ["*" "2A"] ["+" "2B"] ["," "2C"] ["-" "2D"] ["." "2E"] ["/" "2F"] ["0" "30"] ["1" "31"] ["2" "32"] ["3" "33"] ["4" "34"] ["5" "35"] ["6" "36"] ["7" "37"] ["8" "38"] ["9" "39"] [":" "3A"] [";" "3B"] ["<" "3C"] ["=" "3D"] [">" "3E"] ["?" "3F"] ["@" "40"] ["A" "41"] ["B" "42"] ["C" "43"] ["D" "44"] ["E" "45"] ["F" "46"] ["G" "47"] ["H" "48"] ["I" "49"] ["J" "4A"] ["K" "4B"] ["L" "4C"] ["M" "4D"] ["N" "4E"] ["O" "4F"] ["P" "50"] ["Q" "51"] ["R" "52"] ["S" "53"] ["T" "54"] ["U" "55"] ["V" "56"] ["W" "57"] ["X" "58"] ["Y" "59"] ["Z" "5A"] ["[" "5B"] ["\\\\" "5C"] ["]" "5D"] ["^" "5E"] ["_" "5F"] ["\`" "60"] ["a" "61"] ["b" "62"] ["c" "63"] ["d" "64"] ["e" "65"] ["f" "66"] ["g" "67"] ["h" "68"] ["i" "69"] ["j" "6A"] ["k" "6B"] ["l" "6C"] ["m" "6D"] ["n" "6E"] ["o" "6F"] ["p" "70"] ["q" "71"] ["r" "72"] ["s" "73"] ["t" "74"] ["u" "75"] ["v" "76"] ["w" "77"] ["x" "78"] ["y" "79"] ["z" "7A"] ["{" "7B"] ["|" "7C"] ["}" "7D"] ["~" "7E"] ["\\u007f" "7F"]]

; A piece of a literal's text: a run of its characters (\`:raw\`), or one
; character as its code point (\`:cp\`). A run is cut at each place it
; holds a character, which is put back as its code point between the
; pieces, and the empty runs are left out.
def gbnf-raw-seg [s]
  record
    entry :raw s

def gbnf-cp-seg [h]
  record
    entry :cp h

def gbnf-cut-seg [c h seg]
  match (kind (get :raw seg))
    case :string
      let [pieces (split c (get :raw seg))]
        gbnf-flat (map (fn [i] (match i (case 0 [(gbnf-raw-seg (gbnf-at pieces 0))]) (case _ [(gbnf-cp-seg h) (gbnf-raw-seg (gbnf-at pieces i))]))) (indices pieces))
    case _ [seg]

def gbnf-kept-seg [seg]
  match (get :raw seg)
    case "" false
    case _ true

; The sixteen hexadecimal digits, and the 256 pairs of them.
def gbnf-hex-digits ["0" "1" "2" "3" "4" "5" "6" "7" "8" "9" "A" "B" "C" "D" "E" "F"]

def gbnf-hex-pairs
  gbnf-flat (map (fn [a] (map (fn [b] (string-join "" [a b])) gbnf-hex-digits)) gbnf-hex-digits)

; ---- token names

; The name the compiler derives for a literal's token: the text in
; capitals, each character that is not a letter or a digit an underscore,
; the underscores at either end taken off, \`T\` when nothing is left, and a
; number after it when the name is taken. A token with any other name is a
; rule the compiler lifted to a token.
def gbnf-upper-pairs [["a" "A"] ["b" "B"] ["c" "C"] ["d" "D"] ["e" "E"] ["f" "F"] ["g" "G"] ["h" "H"] ["i" "I"] ["j" "J"] ["k" "K"] ["l" "L"] ["m" "M"] ["n" "N"] ["o" "O"] ["p" "P"] ["q" "Q"] ["r" "R"] ["s" "S"] ["t" "T"] ["u" "U"] ["v" "V"] ["w" "W"] ["x" "X"] ["y" "Y"] ["z" "Z"]]

def gbnf-swap-walk [self pairs s]
  match (count pairs)
    case 0 s
    case _
      let [pair (top pairs)]
        self self (pop pairs) (string-join (gbnf-at pair 1) (split (gbnf-at pair 0) s))

def gbnf-word-chars [[48 57] [65 90] [97 122]]

def gbnf-base-name [text]
  let [up (gbnf-swap-walk gbnf-swap-walk gbnf-upper-pairs text)]
    let [others (filter (fn [ch] (gbnf-not (chars-within gbnf-word-chars (gbnf-at ch 0)))) gbnf-ascii)]
      let [under (gbnf-swap-walk gbnf-swap-walk (map (fn [ch] [(gbnf-at ch 0) "_"]) others) up)]
        let [pieces (split "_" under)]
          let [full (filter (fn [i] (gbnf-full (gbnf-at pieces i))) (indices pieces))]
            match (count full)
              case 0 "T"
              case _
                let [lo (gbnf-at full 0)]
                  let [hi (top full)]
                    string-join "_" (map (fn [i] (gbnf-at pieces i)) (filter (fn [i] (match (gbnf-less i lo) (case true false) (case false (gbnf-not (gbnf-less hi i))))) (indices pieces)))

def gbnf-derived [bare text]
  match (chars-within [[48 57] [65 90] [95 95]] bare)
    case false false
    case true
      match (chars-within [[0 127]] text)
        case false true
        case true
          let [base (gbnf-base-name text)]
            match (gbnf-same bare base)
              case true true
              case false
                match (gbnf-starts base bare)
                  case true (gbnf-digits (gbnf-after base bare))
                  case false false

; Every token name the alternates match, one string.
def gbnf-used [cx]
  let [rules (get :rules cx)]
    string-join ""
      vector
        " "
        string-join " "
          map
            fn [name]
              let [r (get-path (as-path [name]) rules)]
                string-join " " (gbnf-flat (map gbnf-s (gbnf-cat (gbnf-open r) (gbnf-close r))))
            keys rules
        " "

; ---- references written back

; The compiler substitutes a reference that leads an alternative by the
; referenced rule's alternatives, each followed by what followed the
; reference (\`a = b "x"\`, \`b = "y" / "z"\` compiles \`a\` as \`"y" "x" / "z"
; "x"\`), and compiles the reference back to the same alternatives. So
; where a run of a rule's alternatives is another rule's alternatives,
; each followed by one same tail, the reference is written back in their
; place. A candidate is a rule the written file can name, with its
; alternatives' keys; a rule that is one reference (\`a = b\`) is none,
; since the compiler leaves such a rule a reference rather than
; substituting it.
def gbnf-candidates [cx names]
  filter
    fn [c] (gbnf-not (gbnf-alias-keys (get :keys c)))
    map (fn [n] (record (entry :name n) (entry :keys (map (fn [seq] (gbnf-seq-keys cx seq)) (gbnf-alts cx n))))) names

def gbnf-alias-keys [ks]
  match (count ks)
    case 1
      match (count (gbnf-at ks 0))
        case 1 (gbnf-starts "@" (gbnf-at (gbnf-at ks 0) 0))
        case _ false
    case _ false

; Whether alternatives are one alternative of one reference to a rule:
; a rule the compiler leaves as it is.
def gbnf-alias [cx alts]
  match (count alts)
    case 1
      let [seq (gbnf-at alts 0)]
        match (count seq)
          case 1
            match (get :k (gbnf-at seq 0))
              case :ref (gbnf-empty (gbnf-helper-kind cx (get :name (gbnf-at seq 0))))
              case _ false
          case _ false
    case _ false

; Whether the alternative's keys begin with the candidate alternative's,
; and what follows them ("\\u0000" where they do not).
def gbnf-prefix-tail [ks cs]
  match (gbnf-less (count ks) (count cs))
    case true "\\u0000"
    case false
      match (gbnf-same (string-join "\\u0001" (gbnf-take (count cs) ks)) (string-join "\\u0001" cs))
        case true (string-join "\\u0001" (gbnf-drop (count cs) ks))
        case false "\\u0000"

; Whether the candidate's alternatives, each followed by one same tail,
; are the alternatives from position i on.
def gbnf-cand-matches [c ka i]
  let [k (count (get :keys c))]
    match (gbnf-less (count ka) (gbnf-plus i k))
      case true false
      case false
        let [first (gbnf-prefix-tail (gbnf-at ka i) (gbnf-at (get :keys c) 0))]
          match first
            case "\\u0000" false
            case _ (gbnf-none (filter (fn [j] (gbnf-not (gbnf-same (gbnf-prefix-tail (gbnf-at ka (gbnf-plus i j)) (gbnf-at (get :keys c) j)) first))) (indices (get :keys c))))

; The candidate, other than the rule itself, whose alternatives stand at
; position i: where several do, the one with the most alternatives, and
; among those the one the spec defines first. The spec cannot tell \`a = b
; ";"\` with \`b = c "("\` from \`a = c "(" ";"\`, nor a reference from two
; rules that begin alike by chance; a grammar written from the top down
; defines the rule an author named before the ones it is made of.
def gbnf-cand-at [cands ka i self]
  let [hits (filter (fn [c] (match (gbnf-same (get :name c) self) (case true false) (case false (gbnf-cand-matches c ka i)))) cands)]
    let [most (filter (fn [c] (gbnf-none (filter (fn [d] (gbnf-less (count (get :keys c)) (count (get :keys d)))) hits))) hits)]
      match (count most)
        case 0 null
        case _ (gbnf-at most 0)

; A rule's alternatives with the references written back: each run a
; candidate covers, from the first position one stands at that no other
; run covers, written as the reference and the tail; the alternatives
; as they are where no run is found, and where writing one back would
; leave the rule one reference, which the compiler would not substitute.
def gbnf-unsub [cx cands self alts]
  match (count cands)
    case 0 alts
    case _
      let [ka (map (fn [seq] (gbnf-seq-keys cx seq)) alts)]
        let [best (map (fn [i] (gbnf-cand-at cands ka i self)) (indices alts))]
          let [covers (fn [j i] (match (kind (gbnf-at best j)) (case :record (match (gbnf-less j i) (case true (gbnf-less i (gbnf-plus j (count (get :keys (gbnf-at best j)))))) (case false false))) (case _ false)))]
            let [accepted (map (fn [i] (match (kind (gbnf-at best i)) (case :record (gbnf-none (filter (fn [j] (covers j i)) (indices alts)))) (case _ false))) (indices alts))]
              let [out (gbnf-flat (map (fn [i] (gbnf-unsub-at cx alts best accepted covers i)) (indices alts)))]
                match (gbnf-alias cx out)
                  case true alts
                  case false out

def gbnf-unsub-at [cx alts best accepted covers i]
  match (gbnf-at accepted i)
    case true
      let [c (gbnf-at best i)]
        vector (gbnf-cat [(gbnf-ref-el (get :name c))] (gbnf-drop (count (gbnf-at (get :keys c) 0)) (gbnf-at alts i)))
    case false
      match (gbnf-some (filter (fn [j] (match (gbnf-at accepted j) (case true (covers j i)) (case false false))) (indices alts)))
        case true []
        case false [(gbnf-at alts i)]

; ---- GBNF's terminals

; The control characters' two-digit escapes, the JSON form's lower-case
; digits beside GBNF's capitals.
def gbnf-hex-pairs-lower
  map gbnf-hex-lower gbnf-hex-pairs

; A piece of a string's JSON form that holds no escaped backslash, with
; JSON's escapes that GBNF spells otherwise rewritten: \`\\b\` and \`\\f\` as
; \`\\x08\` and \`\\x0C\`, and \`\\u00XX\`, the other control characters, as
; \`\\xXX\`.
def gbnf-from-json-piece [piece]
  let [bf (string-join "\\\\x0C" (split "\\\\f" (string-join "\\\\x08" (split "\\\\b" piece))))]
    let [parts (split "\\\\u00" bf)]
      string-join ""
        gbnf-cat
          [(gbnf-at parts 0)]
          map (fn [p] (gbnf-control-escape p)) (gbnf-rest parts)

def gbnf-control-escape [p]
  let [found (filter (fn [h] (gbnf-starts h p)) gbnf-hex-pairs-lower)]
    match (count found)
      case 0 (string-join "" ["\\\\u00" p])
      case _ (string-join "" ["\\\\x" (gbnf-hex-upper (gbnf-at found 0)) (gbnf-after (gbnf-at found 0) p)])

; A literal as a GBNF string: the quote and the backslash escaped, a line
; feed, a carriage return and a tab by their letters, the other control
; characters (C0, DEL and C1) as \`\\xXX\`, everything else as it is.
def gbnf-string [text]
  let [q (quoted text)]
    let [inner (gbnf-before "\\"" (gbnf-after "\\"" q))]
      string-join "" ["\\"" (gbnf-c1 (string-join "\\\\\\\\" (map gbnf-from-json-piece (split "\\\\\\\\" inner)))) "\\""]

; DEL and the C1 controls, which JSON leaves as they are, as \`\\xXX\`.
def gbnf-c1-chars [127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159]

def gbnf-c1 [s]
  match (chars-within [[0 126] [160 1114111]] s)
    case true s
    case false (gbnf-c1-walk gbnf-c1-walk gbnf-c1-chars s)

def gbnf-c1-walk [self codes s]
  match (count codes)
    case 0 s
    case _
      let [h (gbnf-hex-upper (gbnf-at gbnf-hex-pairs-lower (top codes)))]
        self self (pop codes) (string-join (string-join "" ["\\\\x" h]) (split (unquoted (string-join "" ["\\"\\\\u00" (gbnf-hex-lower h) "\\""])) s))

; A case-insensitive literal (ABNF's default) as GBNF, which has none:
; each ASCII letter a class of its two cases, each run of other characters
; a string, which matches exactly what the literal matches. A letter past
; ASCII has no one right expansion, and is refused.
def gbnf-fold-cut [self pairs segs]
  match (count pairs)
    case 0 segs
    case _
      let [pair (top pairs)]
        let [mark (string-join "" ["[" (gbnf-at pair 0) (gbnf-at pair 1) "]"])]
          self self (pop pairs) (gbnf-fold-split (gbnf-at pair 1) mark (gbnf-fold-split (gbnf-at pair 0) mark segs))

def gbnf-fold-split [c mark segs]
  filter gbnf-kept-seg (gbnf-flat (map (fn [seg] (gbnf-cut-seg c mark seg)) segs))

; The characters whose cases a case-insensitive literal's pattern does not
; fold, which a string matches exactly: ASCII, whose letters are written
; as the classes of their two cases, and the characters past U+FFFF but
; those of the scripts that have cases (Deseret, Osage, Vithkuqi, Old
; Hungarian, Garay, Warang Citi, Medefaidrin, Adlam). A character of the
; Basic Multilingual Plane past ASCII may have cases, and is refused.
def gbnf-caseless [[0 127] [65536 66559] [66640 66735] [66816 66927] [67008 68735] [68864 68927] [69008 71839] [71936 93759] [93856 125183] [125280 1114111]]

def gbnf-folded [text]
  match (chars-within gbnf-caseless text)
    case false (gbnf-fail (string-join "" ["the case-insensitive literal " (quoted text) " holds a character past ASCII that may have cases, which GBNF cannot spell"]))
    case true
      map
        fn [seg]
          match (kind (get :raw seg))
            case :string (gbnf-string (get :raw seg))
            case _ (get :cp seg)
        gbnf-fold-cut gbnf-fold-cut gbnf-upper-pairs [(gbnf-raw-seg text)]

; A literal's GBNF items: one string where the match is exact, a
; sequence where it folds case.
def gbnf-lit-items [text cs]
  match cs
    case true [(gbnf-string text)]
    case false (gbnf-folded text)

; A class's member, \`\\uXXXX\` or \`\\u{X...}\`, as \`render_gbnf\` writes it: a
; printable character as itself, the five that mean something inside a
; class escaped, a control character as \`\\xXX\`, a line feed, a carriage
; return and a tab by their letters, a surrogate by its escape, and a
; character past U+FFFF as \`\\UXXXXXXXX\`.
def gbnf-surrogate [h]
  gbnf-some (filter (fn [p] (gbnf-starts p h)) ["d8" "d9" "da" "db" "dc" "dd" "de" "df"])

def gbnf-member [e]
  let [u (gbnf-after "\\\\u" e)]
    match (gbnf-starts "{" u)
      case true
        let [hex (gbnf-hex-lower (gbnf-before "}" (gbnf-after "{" u)))]
          match (gbnf-less 4 (length hex))
            case true (string-join "" ["\\\\U" (match (length hex) (case 5 "000") (case _ "00")) (gbnf-hex-upper hex)])
            case false (gbnf-bmp-member (string-join "" [(match (length hex) (case 1 "000") (case 2 "00") (case 3 "0") (case _ "")) hex]))
      case false (gbnf-bmp-member (gbnf-hex-lower u))

def gbnf-bmp-member [h]
  match h
    case "005d" "\\\\]"
    case "005b" "\\\\["
    case "005c" "\\\\\\\\"
    case "002d" "\\\\u002D"
    case "005e" "\\\\u005E"
    case "000a" "\\\\n"
    case "000d" "\\\\r"
    case "0009" "\\\\t"
    case _
      match (gbnf-surrogate h)
        case true (string-join "" ["\\\\u" (gbnf-hex-upper h)])
        case false
          let [c (unquoted (string-join "" ["\\"\\\\u" h "\\""]))]
            match (chars-within [[0 31] [127 159]] c)
              case true (string-join "" ["\\\\x" (gbnf-hex-upper (gbnf-after "00" h))])
              case false c

; A class's pattern as GBNF: \`.\` for \`[\\s\\S]\`, and otherwise its members
; and ranges, each member as \`gbnf-member\` writes it.
def gbnf-class-text [pat]
  match pat
    case "[\\\\s\\\\S]" "."
    case _
      let [body (gbnf-before "]" (gbnf-after "[" pat))]
        let [negated (gbnf-starts "^" body)]
          let [members (gbnf-rest (split "\\\\u" (match negated (case true (gbnf-after "^" body)) (case false body))))]
            string-join ""
              vector
                "["
                match negated
                  case true "^"
                  case false ""
                string-join "" (map (fn [m] (match (gbnf-ends "-" m) (case true (string-join "" [(gbnf-member (string-join "" ["\\\\u" (gbnf-before "-" m)])) "-"])) (case false (gbnf-member (string-join "" ["\\\\u" m]))))) members)
                "]"

; ---- GBNF's elements

; A rule name GBNF can spell: letters, digits, \`_\` and \`-\`.
def gbnf-legal-name [name]
  match name
    case "" false
    case _ (chars-within [[45 45] [48 57] [65 90] [95 95] [97 122]] name)

def gbnf-ref-text [name]
  match (gbnf-legal-name name)
    case true name
    case false (gbnf-fail (string-join "" ["the rule " (quoted name) " has a name GBNF cannot spell"]))

; Whether a token is a rule the compiler lifted: a literal's token whose
; name is not the one the literal gives it, or that nothing references,
; and whose name GBNF can spell.
def gbnf-lifted [cx used t]
  let [info (gbnf-token cx t)]
    match (get :k info)
      case :lit
        match (gbnf-legal-name (gbnf-bare t))
          case false false
          case true
            match (gbnf-derived (gbnf-bare t) (get :text info))
              case false true
              case true (gbnf-not (gbnf-some (gbnf-rest (split (string-join "" [" " t " "]) used))))
      case _ false

; A token's GBNF items: the rule it was lifted from, a literal's string or
; folded sequence, a class.
def gbnf-token-items [cx lifted t]
  match (gbnf-among t lifted)
    case true [(gbnf-bare t)]
    case false
      let [info (gbnf-token cx t)]
        match (get :k info)
          case :lit (gbnf-lit-items (get :text info) (get :cs info))
          case :class [(gbnf-class-text (get :pat info))]
          case :engine (gbnf-fail (string-join "" ["the token " t " is the engine's own " (get :name info) ", which no GBNF terminal matches"]))

def gbnf-rep-text [self cx lifted name]
  let [parts (gbnf-rep-parts cx name)]
    let [min (gbnf-num (get :min parts))]
      let [count-text (match (get :max parts) (case "" (string-join "" ["{" min ",}"])) (case max (match (gbnf-same min max) (case true (string-join "" ["{" min "}"])) (case false (string-join "" ["{" min "," max "}"])))))]
        string-join "" [(self self cx lifted :atom (get :item parts)) count-text]

; The element a postfix applies to: a terminal, a rule, a group, or
; another postfixed element, which GBNF chains (\`x*?\`); a folded literal
; of more than one item is put in parentheses, as \`render_gbnf\` puts it.
def gbnf-atom-text [self cx lifted el]
  match (get :k el)
    case :tok
      let [items (gbnf-token-items cx lifted (get :name el))]
        match (count items)
          case 1 (gbnf-at items 0)
          case _ (string-join "" ["(" (string-join " " items) ")"])
    case _ (self self cx lifted :el el)

def gbnf-el-text [self cx lifted el]
  match (get :k el)
    case :tok (string-join " " (gbnf-token-items cx lifted (get :name el)))
    case :tail (string-join "" ["(" (self self cx lifted :alts [(get :seq el)]) ")?"])
    case :grp (string-join "" ["(" (self self cx lifted :alts [(get :seq el)]) ")"])
    case :ref
      let [name (get :name el)]
        match (gbnf-helper-kind cx name)
          case "" (gbnf-ref-text name)
          case "star" (string-join "" [(self self cx lifted :atom (gbnf-loop-item cx name (gbnf-rule cx name))) "*"])
          case "plus"
            let [seq (gbnf-at (gbnf-alts cx name) 0)]
              string-join "" [(self self cx lifted :atom (gbnf-at seq 0)) "+"]
          case "opt"
            let [inner (gbnf-at (gbnf-filled (gbnf-alts cx name)) 0)]
              string-join "" [(self self cx lifted :atom inner) "?"]
          case "rep" (gbnf-rep-text self cx lifted name)
          case "group" (string-join "" ["(" (self self cx lifted :alts (gbnf-alts cx name)) ")"])
          case kind (gbnf-fail (string-join "" ["the rule " name " is a helper of a kind the render does not read (" kind ")"]))

def gbnf-seq-text [self cx lifted seq]
  string-join " " (map (fn [el] (self self cx lifted :el el)) seq)

; The text of a rule's or a group's alternatives (\`:alts\`, GBNF's \`|\`
; between them, nothing for an empty one), of an element (\`:el\`) and of
; the element a postfix applies to (\`:atom\`): the one function the render
; recurses through, as \`self\`, a helper's alternatives a level deeper.
def gbnf-text [self cx lifted mode x]
  match mode
    case :alts (string-join " | " (map (fn [seq] (gbnf-seq-text self cx lifted seq)) x))
    case :el (gbnf-el-text self cx lifted x)
    case :atom (gbnf-atom-text self cx lifted x)

; ---- the file

def gbnf-production [cx cands lifted name]
  string-join "" [(gbnf-ref-text name) " ::= " (gbnf-text gbnf-text cx lifted :alts (gbnf-unsub cx cands name (gbnf-alts cx name)))]

def gbnf-lifted-production [cx t]
  let [info (gbnf-token cx t)]
    string-join "" [(gbnf-ref-text (gbnf-bare t)) " ::= " (string-join " " (gbnf-lit-items (get :text info) (get :cs info)))]

; The grammar's start rule: the one the start wrapper pushes, or the rule
; \`options.rule.start\` names where it is no wrapper.
def gbnf-start-rule [cx]
  let [r (gbnf-rule cx (get :start cx))]
    match (gbnf-wrapper r)
      case true (gbnf-p (gbnf-at (gbnf-open r) 0))
      case false (get :start cx)

; A rule the compiler lifted to a token is written under the token's name,
; which no rule of the spec may hold already, nor the \`root\` a written
; start line takes: two productions of one name are one rule.
def gbnf-check-lifted [cx taken lifted]
  map
    fn [t]
      match (match (gbnf-has cx (gbnf-bare t)) (case true true) (case false (gbnf-among (gbnf-bare t) taken)))
        case true (gbnf-fail (string-join "" ["the token " t " is written as a rule named " (gbnf-bare t) ", the name of another rule the text holds"]))
        case false t
    lifted

; GBNF's start rule is \`root\`: a spec whose start rule has another name
; is written with \`root ::= <start>\` first, and one that has a \`root\` that
; is not its start rule cannot be written.
def gbnf-root-lines [names start]
  match start
    case "root" []
    case _
      match (gbnf-among "root" names)
        case true (gbnf-fail (string-join "" ["the start rule is " start ", and GBNF starts from the rule named root, which is another"]))
        case false [(string-join "" ["root ::= " (gbnf-ref-text start)])]

def gbnf-file [spec]
  let [cx (gbnf-context spec)]
    let [checked (gbnf-check spec cx)]
      let [names (filter (fn [n] (gbnf-not (gbnf-made cx n))) (keys (get :rules cx)))]
        let [start (gbnf-start-rule cx)]
          let [used (gbnf-used cx)]
            let [tokens (gbnf-cat (keys (get :fixed cx)) (keys (get :match cx)))]
              let [lifted (gbnf-check-lifted cx (match start (case "root" []) (case _ ["root"])) (filter (fn [t] (gbnf-lifted cx used t)) tokens))]
                let [cands (gbnf-candidates cx names)]
                  string-join ""
                    vector
                      string-join "\\n" (gbnf-flat [(gbnf-root-lines names start) (map (fn [n] (gbnf-production cx cands lifted n)) names) (map (fn [t] (gbnf-lifted-production cx t)) lifted)])
                      "\\n"

def gbnf-render [input]
  concat-map gbnf-file (select root input)
` })
})

function translate (): TranslationParts | undefined {
  return TRANSLATION
}

export {
  translate,
}

export type {
  TranslationPart,
  TranslationParts,
}
